### PR TITLE
vmm: Create a single VFIO container

### LINKED ISSUE #3078: Partially pass through iommu group is allowed / Cannot pass through multiple devices in one iommu group
**Describe the bug**
1. passing a single device through in a multi device iommu group to boot a vm is allowed, this is likely unsafe to host?
2. passing through a graphic card and it's audio card will result in cloud-hypervisor attempting to open the same vfio device twice through rust-vmm/vfio-ioctls

**To Reproduce**
```
--device path=/sys/bus/pci/devices/0000:01:00.0/
# will boot with a partial iommu group
--device path=/sys/bus/pci/devices/0000:01:00.0/ path=/sys/bus/pci/devices/0000:01:00.1/
# will prompt an error as the second attempt of accessing the one vfio device(group) fails
```

The current code base simply does not attempt to take care of iommu groups, it'll only try to dma each pci device's iommu group
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/4d52a84ef7ce751f583053b259df6077bf02394f/vmm/src/device_manager.rs#L2946

**Version**
cloud-hypervisor v17.0-dirty

built from source after changing a few cargo files pointing to rust-vmm, with their recent branch name change

### PR DESCRIPTION
**Pull request by sboeuf**
For most use cases, there is no need to create multiple VFIO containers
as it causes unwanted behaviors. Especially when passing multiple
devices from the same IOMMU group, we need to use the same container so
that it can properly list the groups that have been already opened. The
correct logic was already there in vfio-ioctls, but it was incorrectly
used from our VMM implementation.

For the special case where we put a VFIO device behind a vIOMMU, we must
create one container per device, as we need to control the DMA mappings
per device, which is performed at the container level. Because we must
keep one container per device, the vIOMMU use case prevents multiple
devices attached to the same IOMMU group to be passed through the VM.
But this is a limitation that we are fine with, especially since the
vIOMMU doesn't let us group multiple devices in the same group from a
guest perspective.

Fixes #3078 #3113

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
I tested with baremetal VFIO CI, this is passing fine.

File: vmm/src/device_manager.rs [hunk 1]
```diff
@@ -2830,31 +2823,96 @@ impl DeviceManager {
...
+            } else {
+                return Err(DeviceManagerError::MissingVirtualIommu);
             }
+
+            vfio_container
+        } else if let Some(vfio_container) = &self.vfio_container {
+            Arc::clone(vfio_container)
         } else {
+            let vfio_container = self.create_vfio_container()?;
+
```
Comment (rbradford) [inline vmm/src/device_manager.rs:2879]: nit: Perhaps a bit too much whitespace?

**Review by rbradford — APPROVED** [review]
Great work!

**Review by rbradford — APPROVED** [review]

**Review by likebreath — APPROVED** [review]
