### PR TITLE
vmm: restore KVM clock before resuming vCPUs

### LINKED ISSUE #7930: vm.resume starts vCPUs before KVM clock is restored, causing ~4 minute hang for Windows/Hyper-V guests
**Describe the bug**

After `vm.restore` + `vm.resume`, Windows guests are completely unresponsive for ~236 seconds (no serial console, no network). After this delay, everything comes alive simultaneously. Linux guests resume almost instantly.

The root cause is a **resume ordering bug** in `vmm/src/vm.rs`. The `resume()` method currently executes:

1. `cpu_manager.resume()` — vCPUs start `KVM_RUN` immediately
2. `vm.set_clock()` — `KVM_SET_CLOCK` called **after** vCPUs are already running
3. `device_manager.resume()` — devices resumed last

This means vCPUs execute guest code with stale KVM clock parameters. For Windows/Hyper-V guests, the Hyper-V Reference TSC page (used for fast timekeeping without VM exits) contains outdated scale/offset values. Windows trusts the TSC page (TscSequence != 0), computes completely wrong timestamps, and all timers/scheduling break. Recovery only happens when a Windows internal watchdog (~4 min) forces clock reassessment.

Note: the `pause()` method correctly saves the clock **before** pausing vCPUs — the resume path should mirror this.

**To Reproduce**

1. Start a Windows 11 VM with `--cpus boot=2,kvm_hyperv=on`
2. Take a snapshot: `ch-remote snapshot file:///path/to/snapshot`
3. Start a new CH instance and restore: `ch-remote restore source_url=file:///path/to/snapshot`
4. Resume: `ch-remote resume`
5. Try to access serial console or ping the VM — unresponsive for ~236 seconds
6. After ~236s, everything works simultaneously

**Version**

```
cloud-hypervisor v50.2 (also reproduced on master/v51)
```

**VM configuration**

```
cloud-hypervisor \
  --firmware CLOUDHV.fd \
  --disk path=windows.qcow2,image_type=qcow2,backing_files=on \
  --cpus boot=2,kvm_hyperv=on \
  --memory size=4G \
  --net tap=tap0,num_queues=2 \
  --serial socket=console.sock --console off
```

Guest OS: Windows 11 25H2 (build 26100)
Host OS: Ubuntu, Linux 6.17.0-1009-gcp, KVM

**Logs**

No errors in CH logs. The VM appears to resume successfully from the hypervisor's perspective. The guest is simply unresponsive internally.

Serial console (SAC) polling shows:
- Before fix: SAC responds after **236 seconds**
- After reordering resume to set_clock → devices → vCPUs: SAC responds in **1 second**

**Suggested fix**

Reorder `Vm::resume()` in `vmm/src/vm.rs`:

```rust
// 1. Restore KVM clock FIRST
self.vm.set_clock(clock)?;
// 2. Resume devices
self.device_manager.resume()?;
// 3. Start vCPUs LAST
self.cpu_manager.resume()?;
```

Branch with fix: https://github.com/CMGS/cloud-hypervisor/tree/fix/resume-clock-ordering

### PR DESCRIPTION
**Pull request by CMGS**
The resume() method previously started vCPUs before calling KVM_SET_CLOCK, causing guests to execute with stale clock parameters. This is particularly problematic for Windows/Hyper-V guests where the TSC reference page contains outdated scale/offset values, leading to ~4 minute hangs after vm.restore.

Reorder resume() to: set_clock → device_manager.resume → cpu_manager.resume. This matches the inverse of pause() which correctly saves the clock before pausing vCPUs.

close #7930

### CODE REVIEW

File: vmm/src/vm.rs [hunk 1]
```diff
@@ -3111,7 +3111,6 @@ impl Pausable for Vm {
             .valid_transition(new_state)
             .map_err(|e| MigratableError::Resume(anyhow!("Invalid transition: {e:?}")))?;
 
-        self.cpu_manager.lock().unwrap().resume()?;
         #[cfg(target_arch = "x86_64")]
```
Comment (phip1611) [inline vmm/src/vm.rs:3116]: I think 
```
// Restore KVM clock BEFORE vCPUs start running, so they see correct
// TSC/kvmclock from the first instruction after resume.
```

was a valid intermediate comment. No need to remove

File: vmm/src/vm.rs [hunk 2]
```diff
@@ -3129,6 +3128,8 @@ impl Pausable for Vm {
 
         self.device_manager.lock().unwrap().resume()?;
 
+        self.cpu_manager.lock().unwrap().resume()?;
```
Comment (phip1611) [inline vmm/src/vm.rs:3132]: you can delete the empty line above

**Comment by phip1611** [comment]
Please check our contribution guidelines (CONTRIBUTING.md). Your commit message should be no longer than 72 chars. Please wrap it!

**Comment by CMGS** [comment]
@phip1611 thanks for your commnets, first time contribute to this hh, already wrap the commit logs and remove the empty line

**Comment by phip1611** [comment]
We think we've seen this bug also in production - nice find!
