### PR TITLE
ci: Make the integration tests fail if images are not valid

### LINKED ISSUE #112: Warning about how to reproduce integration tests locally
I spent a lot of time debugging the integration tests today, trying to understand why on `master` I was not able to run successfully the tests on my machine.
The reason was very simple, the `clear-29810-cloud.img` located in my `$HOME/workloads` directory was already there from some previous testing, and I had used this image for some manual testing in the meantime associated with a `cloudinit.img` file.
The result is that the integration tests were reusing this image, despite the fact it was already provisioned by a previous `cloudinit` image. The freshly created `cloudinit` image from the test was simply ignored.

Should we enforce the removal of the `clear-29810-cloud.img` image from the script? Or should we at least put a warning notifying the user?

/cc @rbradford

### PR DESCRIPTION
**Pull request by sboeuf**
When the CI runs in a brand new VM, there's no problem with the validity
of the images as they just got downloaded from the Azure bucket.

In case of a user who runs the CI locally, while doing some debug, he
might provision the images with cloudinit at some point, and later try
to run the CI based on these same images. What happens is that the CI
might randomly fail because the provisioning will not happen again as
it already happened.

This patch ensures the CI to fail early and show an error message to
notify the user about the validity of the images, based on their
sha1sum.

Fixes #112

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@rbradford FYI I tried to run `qemu-img` multiple times and the `sha1sum` of the resulting image is consistently the same.
Just in case, if we notice some problems with `qemu-img` being inconsistent, I have also uploaded to the Azure bucket the RAW images. This way I can still quickly change the script to download everything from the bucket.

File: scripts/run_integration_tests.sh [hunk 1]
```diff
@@ -29,6 +36,13 @@ if [ ! -f "$CLEAR_OS_RAW_IMAGE" ]; then
     pushd $WORKLOADS_DIR
     time qemu-img convert -p -f qcow2 -O raw $CLEAR_OS_IMAGE_NAME $CLEAR_OS_RAW_IMAGE_NAME
     popd
+else
+    CLEAR_OS_RAW_IMAGE_SHA1SUM_REF="2be37c503cae9994f9b061d67a321b6241a730e5"
+    CLEAR_OS_RAW_IMAGE_SHA1SUM=$(sha1sum $CLEAR_OS_RAW_IMAGE | cut -d ' ' -f 1)
+    if [ "$CLEAR_OS_RAW_IMAGE_SHA1SUM" != "$CLEAR_OS_RAW_IMAGE_SHA1SUM_REF" ]; then
+        echo "ERROR: $CLEAR_OS_RAW_IMAGE has the wrong SHA1SUM $CLEAR_OS_RAW_IMAGE_SHA1SUM (expecting $CLEAR_OS_RAW_IMAGE_SHA1SUM_REF)\nConsider removing $CLEAR_OS_RAW_IMAGE to fix the issue."
+        exit 1
```
Comment (rbradford) [inline scripts/run_integration_tests.sh]: I'd rather you used `sha1sum --check` and checked them all in one go? Maybe from a file in the bucket?

i.e  `curl --silent "https://cloudhypervisorstorage.blob.core.windows.net/images/sha1sums" | sha1sum --check`

Comment (sboeuf) [reply scripts/run_integration_tests.sh]: Oh yeah sounds good I'm gonna do that :)
