### PR TITLE
 pci: fix pci MMCONFIG address parsing 

### LINKED ISSUE #716: vfio: Support PCI extended configuration space
We need to investigate how complex it would be to support exposing the Extended Capabilities from PCI configuration space.
Right now, if passing a PCI device with extended caps like these:
```
        Capabilities: [100 v1] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES- TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
                AERCap: First Error Pointer: 00, GenCap- CGenEn- ChkCap- ChkEn-
        Capabilities: [140 v1] Device Serial Number 68-05-ca-ff-ff-15-84-5c
```
we cannot find them from the guest.

I observed the guest is not even trying to access the PCI config space over `0x100` which is the start of the extended caps list. This might mean that Linux won't even try to access anything over this offset since the device is not attached to a PCIe root complex.

### PR DESCRIPTION
**Pull request by crab2313**
The entire MMCONFIG space is broken since we are regarding it as legacy PCI port io address format. Accessing registers in the extended configuration space results to 0xffffffff in most cases since the bus number is decoded to a number above 0 by mistake. Most devices except VFIO devices with extended configuration space work fine since they are not trying to access the memory mapped MMCONFIG space and accessing PCI config space by port io. 

I can just list the extended capability by `lspci -vvv`. But I'm not sure whether the device is functional properly. 

Fixes #716

### CODE REVIEW

File: pci/src/bus.rs [hunk 1]
```diff
@@ -356,8 +356,29 @@ impl BusDevice for PciConfigMmio {
...
+    const REGISTER_NUMBER_MASK: u32 = 0x3ff;
+
+    let bus_number = ((config_address >> BUS_NUMBER_OFFSET) & BUS_NUMBER_MASK) as usize;
+    let device_number = ((config_address >> DEVICE_NUMBER_OFFSET) & DEVICE_NUMBER_MASK) as usize;
+    let function_number =
+        ((config_address >> FUNCTION_NUMBER_OFFSET) & FUNCTION_NUMBER_MASK) as usize;
+    let register_number =
+        ((config_address >> REGISTER_NUMBER_OFFSET) & REGISTER_NUMBER_MASK) as usize;
+
+    (bus_number, device_number, function_number, register_number)
```
Comment (sboeuf) [inline pci/src/bus.rs]: Could you factorize this into a sub function so that both `parse_mmio_config_address` and `parse_io_config_address` can reuse it.

File: pci/src/bus.rs [hunk 2]
```diff
@@ -356,8 +356,29 @@ impl BusDevice for PciConfigMmio {
...
+// Parse the MMIO address offset to a (bus, device, function, register) tuple.
+fn parse_mmio_config_address(config_address: u32) -> (usize, usize, usize, usize) {
+    const BUS_NUMBER_OFFSET: usize = 20;
+    const BUS_NUMBER_MASK: u32 = 0x00ff;
+    const DEVICE_NUMBER_OFFSET: usize = 15;
+    const DEVICE_NUMBER_MASK: u32 = 0x1f;
+    const FUNCTION_NUMBER_OFFSET: usize = 12;
+    const FUNCTION_NUMBER_MASK: u32 = 0x07;
+    const REGISTER_NUMBER_OFFSET: usize = 2;
+    const REGISTER_NUMBER_MASK: u32 = 0x3ff;
```
Comment (sboeuf) [inline pci/src/bus.rs]: Could you give more feedback (maybe a link to the spec) about these constants?

File: pci/src/configuration.rs [hunk 3]
```diff
@@ -9,8 +9,8 @@ use crate::{MsixConfig, PciInterruptPin};
 use byteorder::{ByteOrder, LittleEndian};
 use std::fmt::{self, Display};
 
-// The number of 32bit registers in the config space, 256 bytes.
-const NUM_CONFIGURATION_REGISTERS: usize = 64;
+// The number of 32bit registers in the config space, 4096 bytes.
+const NUM_CONFIGURATION_REGISTERS: usize = 1024;
```
Comment (sboeuf) [inline pci/src/configuration.rs]: Oh that's perfect! Thanks for fixing this :)

File: pci/src/bus.rs (hunk 2 above)
Comment (crab2313) [reply pci/src/bus.rs]: https://wiki.osdev.org/PCI_Express#Enhanced_Configuration_Mechanism

File: pci/src/bus.rs (hunk 1 above)
Comment (crab2313) [reply pci/src/bus.rs]: ok

File: pci/src/configuration.rs (hunk 3 above)
Comment (crab2313) [reply pci/src/configuration.rs]: :)

File: pci/src/bus.rs [hunk 4]
```diff
@@ -356,8 +356,32 @@ impl BusDevice for PciConfigMmio {
...
+// See https://wiki.osdev.org/PCI_Express#Enhanced_Configuration_Mechanism
+fn parse_mmio_config_address(config_address: u32) -> (usize, usize, usize, usize) {
+    const BUS_NUMBER_OFFSET: usize = 20;
+    const BUS_NUMBER_MASK: u32 = 0x00ff;
+    const DEVICE_NUMBER_OFFSET: usize = 15;
+    const DEVICE_NUMBER_MASK: u32 = 0x1f;
+    const FUNCTION_NUMBER_OFFSET: usize = 12;
+    const FUNCTION_NUMBER_MASK: u32 = 0x07;
+    const REGISTER_NUMBER_OFFSET: usize = 2;
+    const REGISTER_NUMBER_MASK: u32 = 0x3ff;
```
Comment (sboeuf) [inline pci/src/bus.rs]: Is the value for `REGISTER_NUMBER_MASK` a typo? Shouldn't it be `0x3f`?

Comment (crab2313) [reply pci/src/bus.rs]: No, it is not a typo. The length of register segment is 12bit in ECAM. See the link in the comment.

Comment (crab2313) [reply pci/src/bus.rs]: register number should not be limited to 6 bit since we want to access the extended configuration space (4096 bytes) .

File: pci/src/bus.rs [hunk 5]
```diff
@@ -356,8 +356,32 @@ impl BusDevice for PciConfigMmio {
     }
 }
 
+fn shift_and_mask(value: u32, offset: usize, mask: u32) -> usize {
+    ((value >> offset) & mask) as usize
+}
+
+// Parse the MMIO address offset to a (bus, device, function, register) tuple.
+// See https://wiki.osdev.org/PCI_Express#Enhanced_Configuration_Mechanism
```
Comment (sboeuf) [inline pci/src/bus.rs]: Ok so now everything makes sense cause I looked at the proper spec, where I think all the information are contained. It'd be more appropriate to refer to the spec rather than `wiki.osdev.org`.
I found the details about ECAM in section `7.2.2 PCI Express Enhanced Configuration Access Mechanism (ECAM)` from the `Pci Express Base Specification Revision 5.0 Version 1.0`.

Comment (crab2313) [reply pci/src/bus.rs]: It's done already.
