### PR TITLE
tests: Improve test_virtio_block_topology reliability

### LINKED ISSUE #3494: test_virtio_block_topology is flaky on aarch64
I ran into this flake several times, but always on the aarch64 worker:

```
failures:


---- tests::parallel::test_virtio_block_topology stdout ----



==== Start cloud-hypervisor command-line ====


"target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" "--cpus" "boot=1" "--memory" "size=512M" "--kernel" "/root/workloads/Image" "--cmdline" "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1" "--disk" "path=/tmp/chEQBADJ/osdisk.img" "path=/tmp/chEQBADJ/cloudinit" "path=" "--net" "tap=,mac=12:34:56:78:90:39,ip=192.168.57.1,mask=255.255.255.0"


==== End cloud-hypervisor command-line ====





==== Start 'wait_vm_boot' (FAILED) ====


duration ="80.087182231s, timeout = 80s"

listen_addr="0.0.0.0:8057"

expected_guest_addr="192.168.57.2"

message=""

error="EpollWaitTimeout"


==== End 'wait_vm_boot' outout ====



thread 'tests::parallel::test_virtio_block_topology' panicked at 'called `Result::unwrap()` on an `Err` value: WaitForBoot(EpollWaitTimeout)', tests/integration.rs:5055:42

stack backtrace:

   0: rust_begin_unwind

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5

   1: core::panicking::panic_fmt

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14

   2: core::result::unwrap_failed

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5

   3: core::result::Result<T,E>::unwrap

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23

   4: integration::tests::parallel::test_virtio_block_topology::{{closure}}

             at ./tests/integration.rs:5055:17

   5: std::panicking::try::do_call

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40

   6: __rust_try

   7: std::panicking::try

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19

   8: std::panic::catch_unwind

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14

   9: integration::tests::parallel::test_virtio_block_topology

             at ./tests/integration.rs:5054:21

  10: integration::tests::parallel::test_virtio_block_topology::{{closure}}

             at ./tests/integration.rs:5000:9

  11: core::ops::function::FnOnce::call_once

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5

  12: core::ops::function::FnOnce::call_once

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.



==== child exit code: 1 ====



==== Start child stdout ====




==== End child stdout ====



==== Start child stderr ====


cloud-hypervisor: 1.225522ms: <vmm> INFO:vmm/src/lib.rs:1283 -- API request event: VmCreate(Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None }, memory: MemoryConfig { size: 536870912, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/root/workloads/Image" }), initramfs: None, cmdline: CmdlineConfig { args: "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1" }, disks: Some([DiskConfig { path: Some("/tmp/chEQBADJ/osdisk.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }, DiskConfig { path: Some("/tmp/chEQBADJ/cloudinit"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }, DiskConfig { path: None, readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }]), net: Some([NetConfig { tap: None, ip: 192.168.57.1, mask: 255.255.255.0, mac: MacAddr { bytes: [18, 52, 86, 120, 144, 57] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None, pci_segment: 0 }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, numa: None, watchdog: false, platform: None }, poisoned: false, .. }, Sender { .. })

cloud-hypervisor: 1.963843ms: <vmm> INFO:vmm/src/lib.rs:1283 -- API request event: VmBoot(Sender { .. })

cloud-hypervisor: 2.384563ms: <vmm> INFO:vmm/src/memory_manager.rs:1447 -- Creating userspace mapping: 0 -> ffff9e782000 400000, slot 0

cloud-hypervisor: 2.454883ms: <vmm> INFO:vmm/src/memory_manager.rs:1481 -- Created userspace mapping: 0 -> ffff9e782000 400000

cloud-hypervisor: 2.483604ms: <vmm> INFO:vmm/src/memory_manager.rs:1447 -- Creating userspace mapping: 40000000 -> ffff70400000 1fc00000, slot 1

cloud-hypervisor: 2.528244ms: <vmm> INFO:vmm/src/memory_manager.rs:1481 -- Created userspace mapping: 40000000 -> ffff70400000 1fc00000

cloud-hypervisor: 2.556724ms: <vmm> INFO:vmm/src/vm.rs:541 -- Booting VM from config: Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None }, memory: MemoryConfig { size: 536870912, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/root/workloads/Image" }), initramfs: None, cmdline: CmdlineConfig { args: "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1" }, disks: Some([DiskConfig { path: Some("/tmp/chEQBADJ/osdisk.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }, DiskConfig { path: Some("/tmp/chEQBADJ/cloudinit"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }, DiskConfig { path: None, readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }]), net: Some([NetConfig { tap: None, ip: 192.168.57.1, mask: 255.255.255.0, mac: MacAddr { bytes: [18, 52, 86, 120, 144, 57] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None, pci_segment: 0 }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, numa: None, watchdog: false, platform: None }, poisoned: false, .. }

cloud-hypervisor: 3.231325ms: <vmm> INFO:vmm/src/pci_segment.rs:92 -- Adding PCI segment: id=0, PCI MMIO config address: 0x30000000, device area [0x5fc00000-0x3fff5fbfffff

cloud-hypervisor: 3.418045ms: <vmm> INFO:vmm/src/device_manager.rs:1945 -- Creating virtio-block device: DiskConfig { path: Some("/tmp/chEQBADJ/osdisk.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false, pci_segment: 0 }

cloud-hypervisor: 3.820046ms: <vmm> INFO:vmm/src/device_manager.rs:2027 -- Using asynchronous RAW disk file (io_uring)

cloud-hypervisor: 3.846046ms: <vmm> INFO:virtio-devices/src/block.rs:438 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }

cloud-hypervisor: 3.898086ms: <vmm> INFO:vmm/src/device_manager.rs:1945 -- Creating virtio-block device: DiskConfig { path: Some("/tmp/chEQBADJ/cloudinit"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk1"), disable_io_uring: false, pci_segment: 0 }

cloud-hypervisor: 4.024206ms: <vmm> INFO:vmm/src/device_manager.rs:2027 -- Using asynchronous RAW disk file (io_uring)

cloud-hypervisor: 4.045406ms: <vmm> INFO:virtio-devices/src/block.rs:438 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }

cloud-hypervisor: 4.088766ms: <vmm> INFO:vmm/src/device_manager.rs:1945 -- Creating virtio-block device: DiskConfig { path: None, readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk2"), disable_io_uring: false, pci_segment: 0 }

Error booting VM: VmBoot(DeviceManager(NoDiskPath))



==== End child stderr ====

thread 'tests::parallel::test_virtio_block_topology' panicked at 'Test failed', test_infra/src/lib.rs:489:5

stack backtrace:

   0: std::panicking::begin_panic

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:543:12

   1: test_infra::handle_child_output

             at ./test_infra/src/lib.rs:489:5

   2: integration::tests::parallel::test_virtio_block_topology

             at ./tests/integration.rs:5092:13

   3: integration::tests::parallel::test_virtio_block_topology::{{closure}}

             at ./tests/integration.rs:5000:9

   4: core::ops::function::FnOnce::call_once

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5

   5: core::ops::function::FnOnce::call_once

             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

### PR DESCRIPTION
**Pull request by sboeuf**
The test test_virtio_block_topology has been recently failing due to an
error happening in losetup while trying to set the block size. Since
there's no option in losetup for retrying, we took the approach of
programming the expected behavior of creating a loop device relying
directly on the system ioctl LOOP_CONFIGURE. We apply a retry loop based
on the result returned by this ioctl, so that we don't fail on the first
try. We also added a sleep before retrying, hoping this would help the
next iteration to succeed.

Fixes #3494

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -5035,6 +5035,134 @@ mod parallel {
...
+            .read(true)
+            .write(true)
+            .open(LOOP_CTL_PATH)
+            .unwrap();
+
+        // Request a free loop device
+        let loop_device_number = unsafe {
+            libc::ioctl(
+                loop_ctl_file.as_raw_fd(),
+                LOOP_CTL_GET_FREE.try_into().unwrap(),
```
Comment (rbradford) [inline tests/integration.rs:5101]: Add `#[allow(clippy::useless_conversion)]` like https://github.com/cloud-hypervisor/cloud-hypervisor/blob/b440cb7d2330770cd415b63544a371d4caa2db3a/block_util/src/async_io.rs#L67

**Review by rbradford — APPROVED** [review]
