### PR TITLE
memory_manager: Fix address range calculation in MemorySlot

### LINKED ISSUE #1800: Windows memory hotplug
Adding memory does not work:

image

image

### PR DESCRIPTION
**Pull request by weltling**
The patch makes sure care taken of a possible overflow and fixes the subtraction part, while adding a test and a documentation part.

Fixes #1800.

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -5574,6 +5574,20 @@ mod tests {
             .unwrap_or(0);
         }
 
+        fn get_ram_gigs_windows(auth: &PasswordAuth) -> u8 {
```
Comment (sboeuf) [inline tests/integration.rs:5577]: I would prefer the name `get_ram_size_windows()` and make this function return the size in bytes.

File: vmm/src/memory_manager.rs [hunk 2]
```diff
@@ -1810,9 +1810,17 @@ impl Aml for MemoryMethods {
...
+                            &aml::Path::new("MAXH"),
+                            &aml::ONE,
+                            &aml::Path::new("MAXH"),
+                        )],
+                    ),
                     &aml::Subtract::new(
-                        &aml::Path::new("MAXH"),
-                        &aml::Path::new("MAXH"),
+                        &aml::Path::new("MAXL"),
+                        &aml::Path::new("MAXL"),
```
Comment (sboeuf) [inline vmm/src/memory_manager.rs:1823]: Could you please explain what was wrong and the details of the calculation through the commit message?

**Review by sboeuf — COMMENTED** [review]
Very nice :)

File: vmm/src/memory_manager.rs (hunk 2 above)
Comment (rbradford) [reply vmm/src/memory_manager.rs:1823]: Yes, maybe you could show an ASL excerpt of the decompiled DSDT from within the guest.

Comment (weltling) [reply vmm/src/memory_manager.rs:1823]: ACK, I need to figure out how to dump ASL there. What is usually used on Linux for this purpose?

Thanks

Comment (rbradford) [reply vmm/src/memory_manager.rs:1823]: `sudo acpidump  > acpi.out; acpixtract acpi.out; iasl dsdt.dat; cat dsdt.dsl`

Comment (weltling) [reply vmm/src/memory_manager.rs:1823]: I think i can dump it with windbg.

Thanks.

Comment (weltling) [reply vmm/src/memory_manager.rs:1823]: Ah, thanks. Or could dump it on Linux, too, might be easier :)

Thanks.

File: tests/integration.rs (hunk 1 above)
Comment (weltling) [reply tests/integration.rs:5577]: When I change to compare bytes, the reported size is about ~1Mb smaller per slot. The initial size is reported that way, too - 2146267136 instead of 2147483648. It might be that some amount is used for servicing, or perhaps it's something powershell specific. I'll check more.

Thanks.

Comment (weltling) [reply tests/integration.rs:5577]: An update on this - it looks like a constant `1216512`, not per slot. Adding further slots seems to have no effect, the diff doesn't change. As it looks like it's something system reserved and not related to this patch, i'm going to make a correction in teh assert for the time being. I'll follow up on what this amount could be about.

Thanks.

Comment (weltling) [reply tests/integration.rs]: Fixed, thanks.

File: vmm/src/memory_manager.rs (hunk 2 above)
Comment (weltling) [reply vmm/src/memory_manager.rs:1823]: Expanded on this for both the issue and ASL for the MCRS method in the commit message.

Thanks.

File: tests/integration.rs (hunk 1 above)
Comment (weltling) [reply tests/integration.rs]: Hmm, the diff seems to be another number on the CI host - `1081344`. It took another round, i just made it check this constant doesn't go beyond 4mb, so fixed it that way.

Thanks

**Review by sboeuf — APPROVED** [review]
LGTM

**Review by liuw — APPROVED** [review]
Really nice work.
