### PR TITLE
block: qcow: Fix QCOW2 + O_DIRECT writes failing with EINVAL

### LINKED ISSUE #8007: qcow2 + O_DIRECT writes fail with EINVAL after qcow_sync refactor (57e89b04f)
**Describe the bug**

After commit 57e89b04f ("block: qcow: Refactor BackingFile for ownership based decomposition"), the qcow_sync write path bypasses O_DIRECT buffer alignment requirements, causing `pwrite64` to fail with `EINVAL` (errno 22) on storage devices that enforce strict DIO alignment.

The new `write_vectored()` in `block/src/qcow_sync.rs:540` gathers guest iovec data into a plain `Vec<u8>` via `gather_from_iovecs()`, then passes it directly to `pwrite64` on the data file fd. When the disk is opened with `direct=on`, this fd has `O_DIRECT` set, which requires the buffer address, length, and file offset to satisfy the device's logical block alignment. `Vec<u8>` allocated by the standard allocator has no alignment guarantee beyond 1 byte (in practice ~16 bytes from glibc malloc), which does not satisfy the 512-byte or 4096-byte alignment that O_DIRECT requires.

The generic block path in `block/src/lib.rs:495` has proper aligned bounce buffer logic for exactly this case, but the new qcow_sync path does not use it.

The read path (`read_vectored()` at line 477) has the same issue — it allocates a `Vec<u8>` and calls `pread_exact` directly without alignment.

**Before the refactor**, `write_vectored()` delegated to `QcowFile::write_vectored_sync()`, which ultimately went through `RawFile`'s alignment-aware I/O. The refactor decomposed `QcowFile` into separate metadata and raw fd components for lock-free I/O, but dropped the alignment wrapper in the process.

**To Reproduce**

1. Create a qcow2 image on a block device with 4096-byte logical sector size (common in cloud/nested-virt environments)
2. Launch a VM with `--disk path=image.qcow2,direct=on,image_type=qcow2`
3. Any guest write to disk fails with EINVAL

```
cloud-hypervisor \
  --firmware CLOUDHV.fd \
  --disk path=overlay.qcow2,direct=on,image_type=qcow2,backing_files=on \
  --cpus boot=4,kvm_hyperv=on \
  --memory size=16G \
  --net tap=tap0,mac=52:54:00:12:34:56,num_queues=8 \
  --serial tty --console off
```

Guest: Windows 11 25H2 — boots (reads succeed probabilistically) but disk writes fail, Windows appears hung or BSODs with `UNMOUNTABLE_BOOT_VOLUME`.

With Linux guests the symptom is I/O errors on any write operation.

**Why it depends on the host storage backend**

O_DIRECT alignment requirements come from the underlying block device's logical sector size. The alignment is probed at file open time in `block/src/qcow/raw_file.rs:62` (`BLK_ALIGNMENTS: [512, 4096]`).

- **512-byte sector devices** (e.g., GCE Persistent Disk): `Vec<u8>` from malloc happens to be 512-byte aligned often enough that most writes succeed by coincidence. The bug exists but is largely masked.
- **4096-byte sector devices** (e.g., cloud VMs with virtio-blk 4Kn, nested virtualization): malloc almost never returns 4096-byte aligned addresses for small-to-medium allocations, so writes fail deterministically.

This explains why the issue is reliably reproducible on certain cloud providers but not others.

**Version**

```
cloud-hypervisor main branch, any commit after 57e89b04f
```

Confirmed working: v50.2 (before the refactor)
Confirmed broken: current main (0a4be0c1c)

**Bisect result**

Regressed by: 57e89b04f ("block: qcow: Refactor BackingFile for ownership based decomposition")

**Error log**

Continuous write failures visible in cloud-hypervisor log:

```
AsyncWrite(WriteVectored(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
```

**Suggested fix**

The `write_vectored()` and `read_vectored()` paths in `qcow_sync.rs` need to use aligned bounce buffers when the underlying file has `O_DIRECT` alignment requirements, similar to the existing logic in `block/src/lib.rs:495-530`. The alignment value is already tracked in `RawFile::alignment` and can be queried from the `QcowRawFile` that `QcowSync` holds.

A regression test with `direct_io=true` should also be added — current qcow_sync tests all use `QcowDiskSync::new(file, false, ...)`.

### PR DESCRIPTION
**Pull request by weltling**
When a guest issues unaligned writes through a QCOW2 disk with `direct=on`, the `pwrite` syscall fails with EINVAL. O_DIRECT requires buffer address, offset, and length to be aligned to the device logical block size. Windows guests trigger this regularly.

`RawFile` probes the device alignment at open time when `direct_io` is enabled. `QcowSync` uses that value to route I/O through `aligned_pread` and `aligned_pwrite`. These functions allocate properly aligned buffers when needed and pass through with no extra allocation when everything is already aligned.

Based on @CMGS patch from #8007.

#### Tests

Existing QCOW2 tests are extended to run with and without `direct_io`. Additional tests exercise `aligned_pread` and `aligned_pwrite` with aligned and unaligned buffers, offsets, and both 512 and 4096 byte alignment.

The Windows test infrastructure now prepares a QCOW2 overlay backed by the raw Windows image for each test run, exposed through `DiskConfig::qcow2_disk()` and cleaned up on drop.

`test_windows_guest_qcow2_backing_direct` boots a Windows guest from that overlay with `direct=on`, writes, reads and copies randomly filled files of various sizes.

Fixes: #8007

### CODE REVIEW

**Comment by CMGS** [comment]
awesome, no O_DIRECT no aligned pread, LGTM.

**Review by phip1611 — APPROVED** [review]
LGTM - awesome test coverage!

File: block/src/qcow_sync.rs [hunk 1]
```diff
@@ -376,6 +381,83 @@ fn pwrite_all(fd: RawFd, buf: &[u8], offset: u64) -> io::Result<()> {
     Ok(())
 }
 
+/// RAII wrapper for an aligned heap buffer required by O_DIRECT.
+struct AlignedBuf {
```
Comment (phip1611) [inline block/src/qcow_sync.rs]: Please add a unit test for AlignedBuf and run it through miri!

File: block/src/qcow_sync.rs [hunk 2]
```diff
@@ -580,10 +679,27 @@ impl AsyncIo for QcowSync {
...
-                    // SAFETY: iovecs point to valid guest memory buffers
-                    let buf = unsafe { gather_from_iovecs(iovecs, buf_offset, count) };
-                    pwrite_all(self.data_file.as_raw_fd(), &buf, host_offset)
+                    if self.alignment > 0 {
+                        // O_DIRECT, aligned buffer avoids bounce copy.
+                        let mut abuf = AlignedBuf::new(count, self.alignment)
+                            .map_err(AsyncIoError::WriteVectored)?;
+                        // SAFETY: iovecs point to valid guest memory buffers
+                        let data = unsafe { gather_from_iovecs(iovecs, buf_offset, count) };
+                        abuf.as_mut_slice(count).copy_from_slice(&data);
```
Comment (phip1611) [inline block/src/qcow_sync.rs]: Do we have a needless copy here?

because data was just created by gather_from_iovecs(...), and the iovecs could be gathered directly into abuf instead.

right?

**Review by phip1611 — CHANGES_REQUESTED** [review]
Sorry, just found a few things.

File: block/src/qcow_sync.rs (hunk 2 above)
Comment (weltling) [reply block/src/qcow_sync.rs]: Good catch! Replaced with `gather_from_iovecs_into` that gathers directly into the aligned buffer, no intermediate `Vec` allocation.

Thanks!

File: block/src/qcow_sync.rs (hunk 1 above)
Comment (weltling) [reply block/src/qcow_sync.rs]: Added test_aligned_buf_allocation_and_access and test_aligned_buf_size_rounds_up. Both pass under miri.

Thanks

**Comment by weltling** [comment]
> LGTM - awesome test coverage!

Thanks for the review.

With the tests - yep, also one easy way to run QCOW2 test for Windows guest, even if it's an overlay :)

Thanks

**Review by phip1611 — APPROVED** [review]

**Comment by weltling** [comment]
Rebased once more to accommodate the latest test_infra changes and fixed the new integration test. No other change otherwise.

Thanks

File: cloud-hypervisor/tests/integration.rs [hunk 3]
```diff
@@ -8337,6 +8337,73 @@ mod windows {
 
         handle_child_output(r, &output);
     }
+
+    #[test]
+    fn test_windows_guest_qcow2_backing_direct() {
```
Comment (rbradford) [inline cloud-hypervisor/tests/integration.rs:8342]: No guards on this test? Does it work on ARM64 and mshv?

File: test_infra/src/lib.rs [hunk 4]
```diff
@@ -530,6 +539,26 @@ impl DiskConfig for WindowsDiskConfig {
...
+                "-f",
+                "qcow2",
+                "-b",
+                osdisk_path.to_str().unwrap(),
+                "-F",
+                "raw",
+                qcow2_path.to_str().unwrap(),
+            ])
+            .output()
+            .expect("Expect creating qcow2 overlay to succeed");
```
Comment (rbradford) [inline test_infra/src/lib.rs:560]: This doesn't actually check the exit code - just that spawning it worked.

File: block/src/qcow_sync.rs [hunk 5]
```diff
@@ -376,6 +381,83 @@ fn pwrite_all(fd: RawFd, buf: &[u8], offset: u64) -> io::Result<()> {
...
+        // SAFETY: layout has non-zero size.
+        let ptr = unsafe { alloc_zeroed(layout) };
+        if ptr.is_null() {
+            return Err(io::Error::last_os_error());
+        }
+        Ok(AlignedBuf { ptr, layout })
+    }
+
+    fn as_mut_slice(&mut self, len: usize) -> &mut [u8] {
+        // SAFETY: ptr is valid for layout.size() bytes; len <= layout.size().
```
Comment (rbradford) [inline block/src/qcow_sync.rs]: Add assertion checks here and below that the `len <= layout.size()` ?

File: block/src/qcow_sync.rs [hunk 6]
```diff
@@ -376,6 +381,83 @@ fn pwrite_all(fd: RawFd, buf: &[u8], offset: u64) -> io::Result<()> {
...
+
+impl AlignedBuf {
+    fn new(size: usize, alignment: usize) -> io::Result<Self> {
+        let size = size.next_multiple_of(alignment);
+        let layout = Layout::from_size_align(size, alignment)
+            .map_err(|e| io::Error::other(format!("invalid aligned layout: {e}")))?;
+        // SAFETY: layout has non-zero size.
+        let ptr = unsafe { alloc_zeroed(layout) };
+        if ptr.is_null() {
+            return Err(io::Error::last_os_error());
```
Comment (rbradford) [inline block/src/qcow_sync.rs]: Does this method actually set errno? Would be surprising to me.

**Review by rbradford — APPROVED** [review]
Just some small things to address.

File: cloud-hypervisor/tests/integration.rs (hunk 3 above)
Comment (weltling) [reply cloud-hypervisor/tests/integration.rs:8342]: Verified this - the guards exist for tests making use of hotplug or API socket. This test does neither, so I'd say no guard is needed.

Thanks

File: test_infra/src/lib.rs (hunk 4 above)
Comment (weltling) [reply test_infra/src/lib.rs:560]: Changed to assert `status.success()`. The rest of the function follows spawn only pattern, but an absent qcow disk would cause a confusing failure indeed.

Thanks

File: block/src/qcow_sync.rs (hunk 5 above)
Comment (weltling) [reply block/src/qcow_sync.rs]: I went for adding `len.min(layout.size())` clamping. The allocation is always rounded up to alignment, so `len` from caller always fits. `Result` return with `if` was considered but seems too heavy for this and the condition seems not likely to occur.

Thanks

File: block/src/qcow_sync.rs (hunk 6 above)
Comment (weltling) [reply block/src/qcow_sync.rs]: Indeed, Rust `alloc_zeroed` doesn't guarantee setting `errno`. Setting `io::Error::new(ErrorKind::OutOfMemory, "aligned allocation failed")` manually.

Thanks!

**Comment by weltling** [comment]
Thanks for the reviews! @rbradford @phip1611 all items addressed. As this patch was introduced before `QcowAsync` came in, it now needed a little reorg.

The original bounce buffer commit has been split into three. The shared helpers live in `qcow_common.rs`, then `qcow_sync.rs` and `qcow_async.rs` each wire them up independently. Both backends now handle O_DIRECT alignment. All the meaningful pieces are deduplicated.

Tests stay in `qcow_sync.rs` because they call the `qcow_common` helpers directly through raw fd operations, not through either backend. Moving them would not change coverage.

Thanks

File: block/src/qcow_common.rs [hunk 7]
```diff
@@ -67,6 +68,98 @@ pub fn pwrite_all(fd: RawFd, buf: &[u8], offset: u64) -> io::Result<()> {
...
+    layout: Layout,
+}
+
+impl AlignedBuf {
+    pub fn new(size: usize, alignment: usize) -> io::Result<Self> {
+        let size = size.next_multiple_of(alignment);
+        let layout = Layout::from_size_align(size, alignment)
+            .map_err(|e| io::Error::other(format!("invalid aligned layout: {e}")))?;
+        // SAFETY: layout has non-zero size.
+        let ptr = unsafe { alloc_zeroed(layout) };
```
Comment (rbradford) [inline block/src/qcow_common.rs:83]: Claude generated: If `size == 0`, `next_multiple_of(alignment)` returns 0 and `alloc_zeroed` with a zero-sized layout is UB per `GlobalAlloc`. The SAFETY comment claims non-zero size but nothing enforces it.
```rust
let size = size.max(1).next_multiple_of(alignment);
```

File: block/src/qcow_async.rs [hunk 8]
```diff
@@ -490,7 +501,7 @@ impl QcowAsync {
                     length,
                 } => {
                     let mut buf = vec![0u8; length as usize];
-                    pread_exact(data_file.as_raw_fd(), &mut buf, host_offset)
+                    aligned_pread(data_file.as_raw_fd(), &mut buf, host_offset, alignment)
                         .map_err(AsyncIoError::ReadVectored)?;
```
Comment (rbradford) [inline block/src/qcow_async.rs]: Claude generated: Plain `Vec<u8>` won't be aligned, so `aligned_pread` always takes the bounce path -- double allocation + extra memcpy. The sync backend uses `AlignedBuf::new(len, alignment)` here to avoid this.

File: block/src/qcow_sync.rs [hunk 9]
```diff
@@ -1451,4 +1637,275 @@ mod unit_tests {
...
+
+    #[test]
+    fn test_aligned_pread_bounce_unaligned_buffer() {
+        // Vec<u8> is not guaranteed to be aligned, so aligned_pread
+        // should use a bounce buffer and still return correct data.
+        let size = 4096usize;
+        let (_tf, fd) = create_pattern_file(size);
+        let alignment = 512;
+
+        let mut buf = vec![0u8; size];
```
Comment (rbradford) [inline block/src/qcow_sync.rs]: Claude generated: Most allocators return page-aligned pointers for 4 KiB allocations, so this likely takes the fast path and never exercises the bounce buffer. Force misalignment:
```rust
let mut backing = vec![0u8; size + 1];
let buf = &mut backing[1..size + 1];
```
Same applies to `test_aligned_pwrite_bounce_unaligned_buffer`.

**Comment by rbradford** [comment]
Sorry for the spam. I was testing a little script I was using to create comments from a claude review and it went awry. I have left three genuine issues.

File: block/src/qcow_common.rs (hunk 7 above)
Comment (weltling) [reply block/src/qcow_common.rs:83]: Indeed, `0usize.next_multiple_of(512)` return 0. Fixed, thanks!

File: block/src/qcow_async.rs (hunk 8 above)
Comment (weltling) [reply block/src/qcow_async.rs]: Changed this to match the sync backend. With no O_DIRECT, it falls back to `pread_exac`t with a plain Vec since no alignment is needed. This makes both parts a little redundant, but the duplication seems marginal.

Thanks

File: block/src/qcow_sync.rs (hunk 9 above)
Comment (weltling) [reply block/src/qcow_sync.rs]: Rewrote as suggested, the concerned tests now allocate `size + 1` bytes and slice at offset 1, misalignment guaranteed.

Thanks

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
@weltling You need a rebase!

**Comment by weltling** [comment]
> @weltling You need a rebase!

Oh, yes, overlooked that. Fixed now.

**Comment by weltling** [comment]
> Sorry for the spam. I was testing a little script I was using to create comments from a claude review and it went awry. I have left three genuine issues.

The script is great, and better more spam than missing bugs :)  I did checks similarly but it didn't catch those points, probably depends on the model or there's yet some else to consider. Quite some learning on that yet.

Thanks!
