### PR TITLE
vmm: Add resizing support for 'memory-zone'

### LINKED ISSUE #1564: cloud-hypervisor panics with hotplug_method=virtio-mem and no hotplug_size
With ACPI:

```
$ target/debug/ch-remote --api-socket=/tmp/api resize --memory 2147483648
Error running command: Server responded with an error: InternalServerError: VmResize(VmResize(MemoryManager(InsufficientHotplugRAM)))
```

With virtio-mem

```
thread 'vmm' panicked at 'should not fail here', vmm/src/memory_manager.rs:828:13
```

### LINKED ISSUE #1593: virtio-mem work not right after reboot
```
clh --console off --serial tty --cmdline "console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda" --kernel /home/teawater/clh/bk/vmlinux --disk path=/home/teawater/kernel/old.img --cpus boot=1 --memory size=128M,hotplug_method=virtio-mem,hotplug_size=256M --net "tap=,mac=,ip=,mask=" --api-socket /home/teawater/clh/api --seccomp=false
cat /proc/meminfo | grep Mem
MemTotal:          98740 kB
MemFree:           76840 kB
MemAvailable:      83844 kB
```

Resize memory to 256m.
```
ch-remote --api-socket=/home/teawater/clh/api resize --memory=$((2*128*1024*1024))
```

```
cat /proc/meminfo | grep Mem
MemTotal:         229812 kB
MemFree:          205740 kB
MemAvailable:     209860 kB

reboot
```

Try to set back guest memory to 128m
```
ch-remote --api-socket=/home/teawater/clh/api resize --memory=$((1*128*1024*1024))
```

It not work.
```
cat /proc/meminfo | grep Mem
MemTotal:         227572 kB
MemFree:          205832 kB
MemAvailable:     210400 kB
```

### LINKED ISSUE #1664: Hotplug support for memory zones
Now that Cloud-Hypervisor can handle specific memory zones, we need to introduce the hot-plug/hot-unplug support to them.
We must define and discuss the way we see this feature being supported and make sure we don't miss some corner cases.

### LINKED ISSUE #1686: virtio-mem region must be aligned on 128MiB and sized on a multiple of 128MiB
The virtio-mem region must not be contiguous with the statically added memory (see #1685)

### PR DESCRIPTION
**Pull request by sboeuf**
This pull request introduces multiple refactoring commits related to `virtio-mem`, but effectively it implements the way to resize `memory-zone` through the new HTTP API `vm.resize-zone`.

One can boot the following VM:
```
./cloud-hypervisor ... --memory size=0,hotplug_method=virtio-mem --memory-zone id=mem0,size=1G,hotplug_size=4G id=mem1,size=1G,hotplug_size=4G
```
which will result in a VM with 2GiB of boot RAM. But each memory zone can be extended up to 5GiB of memory with the following command (`ch-remote`):
```
./ch-remote --api-socket=/tmp/ch.sock resize-zone --id mem0 --size 5G
./ch-remote --api-socket=/tmp/ch.sock resize-zone --id mem1 --size 5G
```
 
Fixes #1564 
Fixes #1593
Fixes #1664
Fixes #1686

### CODE REVIEW

File: vmm/src/memory_manager.rs [hunk 1]
```diff
@@ -64,7 +64,26 @@ struct HotPlugState {
     removing: bool,
 }
 
-pub type MemoryZones = HashMap<String, Vec<Arc<GuestRegionMmap>>>;
+#[derive(Default)]
+pub struct MemoryZone {
+    regions: Vec<Arc<GuestRegionMmap>>,
+    virtiomem_region: Option<Arc<GuestRegionMmap>>,
```
Comment (rbradford) [inline vmm/src/memory_manager.rs:70]: I think s/virtiomem_region/virtio_mem_region/

It scans much better and is more consistent with other parts of the code.

File: vmm/src/memory_manager.rs [hunk 2]
```diff
@@ -485,37 +495,55 @@ impl MemoryManager {
...
+                            Some(virtio_devices::Resize::new().map_err(Error::EventFdFail)?);
+
+                        start_of_device_area = start_addr.unchecked_add(size);
+                    } else {
+                        start_of_device_area = start_of_device_area.unchecked_add(size);
+                    }
+                }
             } else {
-                start_of_device_area = start_of_device_area.unchecked_add(size);
+                return Err(Error::MissingDefaultMemoryZone);
```
Comment (rbradford) [inline vmm/src/memory_manager.rs]: When can this happen?

File: vmm/src/memory_manager.rs [hunk 3]
```diff
@@ -485,37 +495,55 @@ impl MemoryManager {
...
-        let mut virtiomem_resize = None;
-        if let Some(size) = config.hotplug_size {
-            if config.hotplug_method == HotplugMethod::VirtioMem {
-                // Alignment must be "natural" i.e. same as size of block
-                let start_addr = GuestAddress(
-                    (start_of_device_area.0 + virtio_devices::VIRTIO_MEM_DEFAULT_BLOCK_SIZE - 1)
-                        / virtio_devices::VIRTIO_MEM_DEFAULT_BLOCK_SIZE
-                        * virtio_devices::VIRTIO_MEM_DEFAULT_BLOCK_SIZE,
-                );
+        if !use_zones {
```
Comment (rbradford) [inline vmm/src/memory_manager.rs]: So `use_zones` is really `user_provided_zones` since you create a zone and add it to `zones` even when no user provided zone is given...

File: vmm/src/memory_manager.rs [hunk 4]
```diff
@@ -210,11 +210,11 @@ pub enum Error {
     /// No default memory zone found.
     MissingDefaultMemoryZone,
```
Comment (rbradford) [inline vmm/src/memory_manager.rs]: Is this error now unused?

**Comment by rbradford** [comment]
What happens if you do `--memory size=0,hotplug_method=acpi --memory-zone size=4G,hotplug_size=4G` ?

**Review by rbradford — APPROVED** [review]
Good work on something that is pretty hairy! I would prefer some variable name changes. But please do that in additional commit(s) rather than try and modify the old ones.

**Comment by rbradford** [comment]
Is there some scope for splitting out some of the code into individual functions and unit testing those?

**Comment by sboeuf** [comment]
@rbradford 
>What happens if you do --memory size=0,hotplug_method=acpi --memory-zone size=4G,hotplug_size=4G ?

It works, but that means you cannot use `resize`, only `resize-zone` will be usable.

>Is there some scope for splitting out some of the code into individual functions and unit testing those?

I think we could unit test `create_memory_regions_from_zones()` and maybe factorize the update of the list of zones into a dedicated function as well, that might help with unit testing.

>I would prefer some variable name changes. But please do that in additional commit(s) rather than try and modify the old ones.

Thanks that'll be easier to address your comments :)

File: vmm/src/memory_manager.rs (hunk 4 above)
Comment (sboeuf) [reply vmm/src/memory_manager.rs]: It's removed in a further commit.

**Comment by rbradford** [comment]
> @rbradford
> 
> > What happens if you do --memory size=0,hotplug_method=acpi --memory-zone size=4G,hotplug_size=4G ?
> 
> It works, but that means you cannot use `resize`, only `resize-zone` will be usable.

How will `resize-zone` react?

File: vmm/src/memory_manager.rs (hunk 3 above)
Comment (sboeuf) [reply vmm/src/memory_manager.rs]: Yes exactly. Let me change the variable name to clarify this.

**Comment by sboeuf** [comment]
>How will `resize-zone` react?

It will completely ignore it. With `resize-zone` we know we only use `virtio-mem`.

File: vmm/src/memory_manager.rs (hunk 2 above)
Comment (sboeuf) [reply vmm/src/memory_manager.rs]: This is later removed. This was introduced as part of maintaining the behavior for `--memory`, but at some point when introducing support for all zones, this simply goes away.

**Comment by rbradford** [comment]
> > How will `resize-zone` react?
> 
> It will completely ignore it. With `resize-zone` we know we only use `virtio-mem`.

It should respond with an error.

**Comment by sboeuf** [comment]
@rbradford 
>It should respond with an error

But `--memory size=0,hotplug_method=acpi --memory-zone size=4G,hotplug_size=4G` is identical to `--memory size=0 --memory-zone size=4G,hotplug_size=4G` since the default `hotplug_method` is `acpi`.
Do you expect users to specify `virtio-mem` to get the `vm.resize-zone` working? Something like:
`--memory size=0,hotplug_method=virtio-mem --memory-zone size=4G,hotplug_size=4G`
If we go down this road, then we should even return an error sooner (from boot) since it's incompatible to have `hotplug_size` in `--memory-zone` along with `hotplug_method=acpi` in `--memory`.

**Comment by rbradford** [comment]
> @rbradford
> 
> > It should respond with an error
> 
> But `--memory size=0,hotplug_method=acpi --memory-zone size=4G,hotplug_size=4G` is identical to `--memory size=0 --memory-zone size=4G,hotplug_size=4G` since the default `hotplug_method` is `acpi`.
> 
> Do you expect users to specify `virtio-mem` to get the `vm.resize-zone` working?
> Something like:
> `--memory size=0,hotplug_method=virtio-mem --memory-zone size=4G,hotplug_size=4G`
> 
> If we go down this road, then we should even return an error sooner (from boot) since it's incompatible to have `hotplug_size` in `--memory-zone` along with `hotplug_method=acpi` in `--memory`.

Because `hotplug_method=acpi` is the default I think we should make it very clear to the user when they try and do something that's not going work. Silently ignoring a request is not right.

**Comment by sboeuf** [comment]
Supersedes https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1594

**Comment by sboeuf** [comment]
@rbradford CI's green now :)

File: docs/memory.md [hunk 5]
```diff
@@ -112,15 +113,35 @@ _Example_
...
-memory can be added to the VM.
+Value is an unsigned integer of 64 bits. A value of 0 is invalid.
 
 _Example_
 
 ```
 --memory size=1G,hotplug_size=1G
 ```
 
+### `hotplugged_size`
```
Comment (rbradford) [inline docs/memory.md:124]: :+1:

File: docs/memory.md [hunk 6]
```diff
@@ -288,6 +311,43 @@ _Example_
 --memory-zone id=mem0,size=1G,host_numa_node=0
 ```
 
+### `hotplug_size`
+
+Amount of memory that can be dynamically added to the memory zone. Since
+`virtio-mem` is the only way of resizing a memory zone, one must specify
+the `hotplug_method=virtio-mem` from the `--memory` parameter.
```
Comment (rbradford) [inline docs/memory.md:318]: s/from the/to the/

File: vmm/src/api/openapi/cloud-hypervisor.yaml [hunk 7]
```diff
@@ -150,6 +150,22 @@ paths:
...
+        description: The target size for the memory zone
+        content:
+          application/json:
+            schema:
+              $ref: '#/components/schemas/VmResizeZone'
+        required: true
+      responses:
+        204:
+          description: The memory zone was successfully resized.
+        404:
```
Comment (rbradford) [inline vmm/src/api/openapi/cloud-hypervisor.yaml:166]: This must be wrong. Surely we generate a 500 in that case?

File: vmm/src/device_manager.rs [hunk 8]
```diff
@@ -3350,6 +3371,20 @@ impl DeviceManager {
     }
 }
 
+#[cfg(feature = "acpi")]
+fn numa_node_id_from_memory_zone_id(numa_nodes: &NumaNodes, memory_zone_id: &str) -> Option<u32> {
+    for (numa_node_id, numa_node) in numa_nodes.iter() {
```
Comment (rbradford) [inline vmm/src/device_manager.rs:3376]: `.iter()` implements `.find()` so you might be able to simplify this.

**Review by rbradford — APPROVED** [review]
Not as scary as it looks. Just some nits/queries

File: vmm/src/api/openapi/cloud-hypervisor.yaml (hunk 7 above)
Comment (sboeuf) [reply vmm/src/api/openapi/cloud-hypervisor.yaml:166]: Yes you're right.

File: vmm/src/device_manager.rs (hunk 8 above)
Comment (sboeuf) [reply vmm/src/device_manager.rs:3376]: Well since `numa_nodes` is a `HashMap`, I guess `find()` would return `Option<(u32, NumaNode)>` instead of `Option<u32>`. It looks simpler to keep this as it is, don't you think?
