### PR TITLE
vmm: Add support for fixed VHD disk files

### LINKED ISSUE #2185: Add support for the VHD disk image format
[As specified by Microsoft](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/dd323654(v=vs.85)) and used by Azure.

We only want to support fixed VHD for now.

### PR DESCRIPTION
**Pull request by sboeuf**
This PR adds both synchronous and asynchronous support for fixed VHD disk files.

Fixes #2185

### CODE REVIEW

**Comment by sboeuf** [comment]
@rbradford I need to add an integration test for it. I was thinking about using `dd` from `scripts/run_integration_tests...` to create the `VHD` image from our RAW image. What do you think?

**Comment by russell-islam** [comment]
@sboeuf  Can we use qemu-img tool to convert the image to VHD format within the script to test?

**Comment by sboeuf** [comment]
@russell-islam 
>Can we use qemu-img tool to convert the image to VHD format within the script to test?

That was a very nice idea, unfortunately it generates a dynamic VHD file :(

**Comment by rbradford** [comment]
> @russell-islam
> 
> > Can we use qemu-img tool to convert the image to VHD format within the script to test?
> 
> That was a very nice idea, unfortunately it generates a dynamic VHD file :(

I read the qemu-img source code: `qemu-img convert -O vpc -o subformat=fixed focal.raw focal.vhd`

File: scripts/run_integration_tests_aarch64.sh [hunk 1]
```diff
@@ -50,6 +50,14 @@ update_workloads() {
...
     fi
 
+    FOCAL_OS_VHD_IMAGE_NAME="focal-server-cloudimg-arm64-custom.vhd"
+    FOCAL_OS_VHD_IMAGE="$WORKLOADS_DIR/$FOCAL_OS_VHD_IMAGE_NAME"
+    if [ ! -f "$FOCAL_OS_VHD_IMAGE" ]; then
+        pushd $WORKLOADS_DIR
+	time qemu-img convert -p -f raw -O vpc -o subformat=fixed $FOCAL_OS_RAW_IMAGE_NAME $FOCAL_OS_VHD_IMAGE_NAME || exit 1
+        popd
+    fi
+
```
Comment (rbradford) [inline scripts/run_integration_tests_aarch64.sh:60]: It would be so much nicer to do this in the test itself (I know this is how the QCOW2 is done too.) But I would like to see us do it in the test itself so we can reduce the complexity of the script and also only do it when needed.

File: block_util/src/vhd.rs [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+    let footer = match VhdFooter::new(f) {
+        Ok(footer) => footer,
+        Err(e) => {
+            warn!("VhdFooter couldn't be retrieved: {}", e);
+            return false;
+        }
+    };
+
+    footer.disk_type() == 0x2
+}
```
Comment (rbradford) [inline block_util/src/vhd.rs:115]: This is perfect for unit testing. Have a reference footer sector and check the values that come out.

File: block_util/src/raw_sync.rs [hunk 3]
```diff
@@ -65,15 +60,19 @@ impl AsyncIo for RawFileSync {
...
-        )
+        let result = unsafe {
+            libc::preadv(
+                self.fd as libc::c_int,
+                iovecs.as_ptr() as *const libc::iovec,
+                iovecs.len() as libc::c_int,
+                offset,
+            )
+        };
+
```
Comment (rbradford) [inline block_util/src/raw_sync.rs:71]: Are you ignoring the errors here? i.e. result = -1 and errno set.

File: block_util/src/raw_sync.rs [hunk 4]
```diff
@@ -82,25 +81,35 @@ impl AsyncIo for RawFileSync {
...
+        self.completion_list.push((user_data, result as i32));
+        self.eventfd.write(1).unwrap();
+
```
Comment (rbradford) [inline block_util/src/raw_sync.rs:95]: Ditto

File: block_util/src/fixed_vhd_async.rs [hunk 5]
```diff
@@ -0,0 +1,109 @@
+// Copyright © 2021 Intel Corporation
+//
+// SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
```
Comment (rbradford) [inline block_util/src/fixed_vhd_async.rs:3]: New code should be Apache 2.0 unless you copied from code that is derived from elsewhere.

File: block_util/src/raw_sync.rs (hunk 3 above)
Comment (sboeuf) [reply block_util/src/raw_sync.rs:71]: No I'm pushing the result down the completion list, so that the caller will get the result after calling into `complete()`

File: block_util/src/raw_sync.rs (hunk 4 above)
Comment (sboeuf) [reply block_util/src/raw_sync.rs:95]: Same thing here, the result will be retrieve asynchronously after `complete()` is invoked.

File: scripts/run_integration_tests_aarch64.sh (hunk 1 above)
Comment (sboeuf) [reply scripts/run_integration_tests_aarch64.sh:60]: But isn't it better to do this only once, as we might want to run multiple tests using VHD?

File: block_util/src/fixed_vhd_async.rs (hunk 5 above)
Comment (sboeuf) [reply block_util/src/fixed_vhd_async.rs:3]: Ok I'll apply to all new files!

File: block_util/src/raw_sync.rs (hunk 3 above)
Comment (rbradford) [reply block_util/src/raw_sync.rs:71]: But errno might have been overwritten. And this is not what the old code did:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/060df69f072986ef5a7f15a4bde59c3da75b5403/block_util/src/lib.rs#L583

File: scripts/run_integration_tests_aarch64.sh (hunk 1 above)
Comment (rbradford) [reply scripts/run_integration_tests_aarch64.sh:60]: You can still test if it's present. And we only have one QCOW2 and one VHD test and I can't realistically see a need for more.

File: block_util/src/vhd.rs [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+/// Determine image type through file parsing.
+pub fn is_fixed_vhd(f: &mut File) -> bool {
+    let footer = match VhdFooter::new(f) {
+        Ok(footer) => footer,
+        Err(e) => {
+            warn!("VhdFooter couldn't be retrieved: {}", e);
+            return false;
+        }
+    };
+
```
Comment (rbradford) [inline block_util/src/vhd.rs:113]: Check the cookie() matches contectix && foot.disk_type() == 2

File: block_util/src/vhd.rs [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+        self.saved_state
+    }
+}
+
+/// Determine image type through file parsing.
+pub fn is_fixed_vhd(f: &mut File) -> std::io::Result<bool> {
+    let footer = VhdFooter::new(f)?;
+
+    let cookie_bytes = footer.cookie().to_be_bytes();
+    let cookie = match std::str::from_utf8(&cookie_bytes) {
```
Comment (rbradford) [inline block_util/src/vhd.rs:109]: This is bad practice as this function continues reading until \0. As such you're trusting the data you've been given. Instead you should compare the value against "conectix" converted into a u64 either as a hardcoded constant or do it every time. (I would prefer the former.)

Comment (rbradford) [reply block_util/src/vhd.rs:109]: Also the spec says "string" but it's not a string as it's not zero terminated (there's 8 bytes and 8 characters)

Comment (sboeuf) [reply block_util/src/vhd.rs:109]: Oh good point that's cleaner!

File: block_util/src/raw_sync.rs [hunk 8]
```diff
@@ -65,15 +60,22 @@ impl AsyncIo for RawFileSync {
...
-        )
+        let result = unsafe {
+            libc::preadv(
+                self.fd as libc::c_int,
+                iovecs.as_ptr() as *const libc::iovec,
+                iovecs.len() as libc::c_int,
+                offset,
+            )
+        };
+        if result == -1 {
```
Comment (rbradford) [inline block_util/src/raw_sync.rs:71]: Standard practice is `result < 0`

Comment (sboeuf) [reply block_util/src/raw_sync.rs]: Fixed!

File: vmm/src/device_manager.rs [hunk 9]
```diff
@@ -1655,12 +1662,38 @@ impl DeviceManager {
...
+                detect_image_type(&mut file).map_err(DeviceManagerError::DetectImageType)?;
 
-            let image_type = qcow::detect_image_type(&mut raw_img)
-                .map_err(DeviceManagerError::DetectImageType)?;
+            // The O_DIRECT flag has some alignment requirements which are not
+            // met by the detect_image_type() function. That's why the flag is
+            // set after the file has been opened and after we found out about
+            // the image type.
+            if disk_cfg.direct {
+                let ret = unsafe { libc::fcntl(file.as_raw_fd(), libc::F_SETFL, libc::O_DIRECT) };
```
Comment (rbradford) [inline vmm/src/device_manager.rs:1673]: You lose any existing bits set on the file.

Comment (rbradford) [reply vmm/src/device_manager.rs:1673]:
```rust
let flags = unsafe { libc::fcntl(file.as_raw_fd(), libc::F_GETFL};
if flags < 0 {
...
}
let ret =  unsafe { libc::fcntl(file.as_raw_fd(),  libc::F_SETFL, flags | libc::O_DIRECT) };
```

Comment (sboeuf) [reply vmm/src/device_manager.rs]: I got rid of `fnctl` and chose to align the buffers instead.

File: block_util/src/vhd.rs (hunk 2 above)
Comment (sboeuf) [reply block_util/src/vhd.rs:122]: Done!

File: block_util/src/fixed_vhd_sync.rs [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+        Ok(Box::new(
+            FixedVhdSync::new(self.file.as_raw_fd(), self.footer)
+                .map_err(DiskFileError::NewAsyncIo)?,
+        ) as Box<dyn AsyncIo>)
+    }
+}
+
+pub struct FixedVhdSync {
+    raw_file_sync: RawFileSync,
+    vhd_footer: VhdFooter,
```
Comment (rbradford) [inline block_util/src/fixed_vhd_sync.rs:42]: Please just save the u64 file size. None of the other fields are used so we can avoid keeping the footer around.

File: block_util/src/vhd.rs [hunk 11]
```diff
@@ -0,0 +1,223 @@
...
+    current_size: u64,
+    disk_geometry: u32,
+    disk_type: u32,
+    checksum: u32,
+    unique_id: u128,
+    saved_state: u8,
+}
+
+impl VhdFooter {
+    pub fn new(file: &mut File) -> std::io::Result<VhdFooter> {
```
Comment (rbradford) [inline block_util/src/vhd.rs:29]: This function should return an error if it's not valid VHD file.

**Comment by rbradford** [comment]
More generally it seems inefficient to go to all the hassle of creating the footer only to through it all away again and recreate it.

File: block_util/src/lib.rs [hunk 12]
```diff
@@ -652,3 +657,35 @@ pub fn fsync_sync(
...
+    Raw,
+}
+
+const QCOW_MAGIC: u32 = 0x5146_49fb;
+
+/// Determine image type through file parsing.
+pub fn detect_image_type(f: &mut File) -> std::io::Result<ImageType> {
+    // We must create a buffer aligned on 512 bytes with a size being a
+    // multiple of 512 bytes as the file might be opened with O_DIRECT flag.
+    let layout = std::alloc::Layout::from_size_align(512, 512).unwrap();
```
Comment (rbradford) [inline block_util/src/lib.rs:673]: Rather than this manual memory management can you just do?

```rust
#[repr(align(512))]
struct Sector
{
    data: [u8; 512]
}

File: block_util/src/vhd.rs (hunk 11 above)
Comment (sboeuf) [reply block_util/src/vhd.rs:29]: What's a not valid VHD file?

**Comment by sboeuf** [comment]
@rbradford 
>More generally it seems inefficient to go to all the hassle of creating the footer only to through it all away again and recreate it.

Well it's not a huge overhead, and I don't see how we can do it only once without making the detect function VHD specific (which I don't really like).

File: block_util/src/vhd.rs (hunk 11 above)
Comment (rbradford) [reply block_util/src/vhd.rs:29]: Basically the check that `is_fixed_vhd()` does.

File: block_util/src/fixed_vhd_async.rs [hunk 13]
```diff
@@ -0,0 +1,109 @@
...
+        Ok(Box::new(
+            FixedVhdAsync::new(self.file.as_raw_fd(), ring_depth, self.footer)
+                .map_err(DiskFileError::NewAsyncIo)?,
+        ) as Box<dyn AsyncIo>)
+    }
+}
+
+pub struct FixedVhdAsync {
+    raw_file_async: RawFileAsync,
+    vhd_footer: VhdFooter,
```
Comment (rbradford) [inline block_util/src/fixed_vhd_async.rs:42]: You missed this version.

File: block_util/src/vhd.rs (hunk 11 above)
Comment (sboeuf) [reply block_util/src/vhd.rs:29]: No because it will fail on dynamic VHD, and that's not what we want.

File: block_util/src/fixed_vhd_async.rs (hunk 13 above)
Comment (sboeuf) [reply block_util/src/fixed_vhd_async.rs:42]: oh damn :)

File: block_util/src/raw_sync.rs [hunk 14]
```diff
@@ -65,15 +60,22 @@ impl AsyncIo for RawFileSync {
...
-        read_vectored_sync(
-            offset,
-            iovecs,
-            user_data,
-            &mut self.raw_file,
-            &self.eventfd,
-            &mut self.completion_list,
-            &mut self.semaphore,
-        )
+        let result = unsafe {
```
Comment (rbradford) [inline block_util/src/raw_sync.rs:63]: It will be nice to see this lock removed:
```
-   15.21%     0.44%  _disk0_q0        cloud-hypervisor    [.] <block_util::raw_sync::RawFileSync as block_util::async_io::AsyncIo>::read_vectored                                                                                                                                                                           ▒
   - 14.77% <block_util::raw_sync::RawFileSync as block_util::async_io::AsyncIo>::read_vectored                                                                                                                                                                                                                              ▒
      + 7.92% block_util::read_vectored_sync                                                                                                                                                                                                                                                                                 ▒
        2.13% cfree@GLIBC_2.2.5                                                                                                                                                                                                                                                                                              ▒
        1.12% __pthread_mutex_lock                                                                                                                                                                                                                                                                                           ▒
        0.71% __libc_write                                                                                                                                                                                                                                                                                                   ▒
        0.68% __pthread_mutex_unlock_usercnt                                                                                                                                                                                                                                                                                 ▒
        0.67% <qcow::raw_file::RawFile as std::io::Seek>::seek
```

**Review by rbradford — APPROVED** [review]
