### PR TITLE
virtio: fix guest-triggerable panic via OOB queue_select in MSI-X vector access

### LINKED ISSUE #7917: Guest-triggerable VMM panic via unchecked queue_select index in PCI common config MSI-X vector access
A guest VM can crash the Cloud Hypervisor VMM process by performing two MMIO writes to any virtio-PCI device's common configuration space BAR. The queue_msix_vector register access at offset 0x1a indexes into the msix_queues Vec using the guest-controlled queue_select value without bounds checking, causing a panic on out-of-bounds access.

This is a guest-to-host denial of service. No special privileges are required inside the guest.

Affected Code
File: virtio-devices/src/transport/pci_common_config.rs

Read path (line 252):

0x1a => self.msix_queues.lock().unwrap()[self.queue_select as usize],
Write path (line 268):

0x1a => self.msix_queues.lock().unwrap()[self.queue_select as usize] = value,
The queue_select field is a u16 written directly by the guest at offset 0x16 with no validation (line 266):

0x16 => self.queue_select = value,
All other register accesses that depend on queue_select correctly use the bounds-checked helpers with_queue() / with_queue_mut() (lines 379-390), which use .get() / .get_mut(). The MSI-X queue vector access is the only path that bypasses these helpers and indexes the Vec directly.

Trigger
From inside the guest (no root required if the PCI BAR is user-mappable via sysfs):

import mmap, os, struct

fd = os.open("/sys/bus/pci/devices/0000:00:01.0/resource0", os.O_RDWR | os.O_SYNC)
mm = mmap.mmap(fd, 0x80000, mmap.MAP_SHARED, mmap.PROT_READ | mmap.PROT_WRITE)

# Step 1: set queue_select to out-of-bounds value
struct.pack_into('<H', mm, 0x16, 0xFFFF)

# Step 2: read queue_msix_vector — triggers msix_queues[65535] panic
val = struct.unpack_from('<H', mm, 0x1a)[0]
The VMM panics with:

thread panicked at 'index out of bounds: the len is N but the index is 65535'
The vCPU thread's catch_unwind catches the panic and signals an orderly VM shutdown via exit_evt.

Impact
Guest-to-host DoS: Any guest VM can terminate its own VMM process
Affects all virtio-PCI devices: Every device (virtio-blk, virtio-net, virtio-rng, etc.) exposes the same common config code
No guest privileges required: The PCI BAR is accessible from guest userspace via /sys/bus/pci/devices/.../resource0
Trivially exploitable: Two MMIO writes with no timing or race conditions
This is DoS only. Rust's bounds checking prevents the out-of-bounds memory from ever being accessed — the panic fires before any read or write occurs. There is no information leak or code execution.

Suggested Fix
// Line 252 — replace direct index with bounds-checked .get():
0x1a => self.msix_queues.lock().unwrap()
    .get(self.queue_select as usize)
    .copied()
    .unwrap_or(0),

// Line 268 — same for write path:
0x1a => {
    let mut queues = self.msix_queues.lock().unwrap();
    if let Some(entry) = queues.get_mut(self.queue_select as usize) {
        *entry = value;
    }
},
This matches the pattern already used by with_queue() and with_queue_mut() for all other queue_select-dependent accesses.

Additional Recommendations
Consider adding #[deny(clippy::indexing_slicing)] to the transport module to catch similar issues at compile time.
The PCI transport layer has no fuzz coverage in fuzz/fuzz_targets/. A fuzzer exercising VirtioPciCommonConfig::read() / write() with adversarial (offset, data) pairs would have caught this immediately.
Environment
Tested on: Cloud Hypervisor main at commit e1e6d0a (2026-03-27)
Also present in: Latest release v51.1
Guest: Ubuntu 24.04, kernel 6.18.15
Host CPU: AMD EPYC Milan
Confirmed by: Triggering the panic from inside a guest VM; the VM was terminated

### PR DESCRIPTION
**Pull request by kaessert**
The queue_msix_vector register (offset 0x1a in virtio PCI common config) indexed into the msix_queues Vec using the guest-controlled queue_select value without bounds checking:

  0x1a => self.msix_queues.lock().unwrap()[self.queue_select as usize],

A guest can set queue_select to any u16 value via offset 0x16, then read or write offset 0x1a to trigger an out-of-bounds Vec index panic, crashing the VMM process. No special privileges are required inside the guest (the PCI BAR is accessible from userspace via sysfs).

All other queue_select-dependent accesses correctly use the bounds- checked with_queue()/with_queue_mut() helpers which use .get()/.get_mut(). The MSI-X vector access was the only path that bypassed these helpers.

Fix by replacing direct Vec indexing with .get()/.copied().unwrap_or(0) for the read path and .get_mut() for the write path, matching the pattern used everywhere else in VirtioPciCommonConfig.

Add a regression test that sets queue_select to 0xFFFF and verifies that reading and writing offset 0x1a does not panic.

fixes #7917

### CODE REVIEW

File: virtio-devices/src/transport/pci_common_config.rs [hunk 1]
```diff
@@ -249,7 +249,7 @@ impl VirtioPciCommonConfig {
             0x12 => queues.len() as u16, // num_queues
             0x16 => self.queue_select,
             0x18 => self.with_queue(queues, |q| q.size()).unwrap_or(0),
-            0x1a => self.msix_queues.lock().unwrap()[self.queue_select as usize],
+            0x1a => self.msix_queues.lock().unwrap().get(self.queue_select as usize).copied().unwrap_or(0),
```
Comment (phip1611) [inline virtio-devices/src/transport/pci_common_config.rs]: why don't you use the `with_queue` helper here?

File: virtio-devices/src/transport/pci_common_config.rs [hunk 2]
```diff
@@ -265,7 +265,11 @@ impl VirtioPciCommonConfig {
             0x10 => self.msix_config.store(value, Ordering::Release),
             0x16 => self.queue_select = value,
             0x18 => self.with_queue_mut(queues, |q| q.set_size(value)),
-            0x1a => self.msix_queues.lock().unwrap()[self.queue_select as usize] = value,
+            0x1a => {
+                if let Some(entry) = self.msix_queues.lock().unwrap().get_mut(self.queue_select as usize) {
```
Comment (phip1611) [inline virtio-devices/src/transport/pci_common_config.rs]: or here?

File: virtio-devices/src/transport/pci_common_config.rs (hunk 1 above)
Comment (phip1611) [inline virtio-devices/src/transport/pci_common_config.rs]:
```suggestion
            0x1a => self.msix_queues.lock().unwrap().get(self.queue_select as usize).copied().unwrap_or(0xff),
```

isn't 0xff the default PCI value for not set?

Comment (kaessert) [reply virtio-devices/src/transport/pci_common_config.rs]: Regarding with_queue / with_queue_mut: those helpers operate on the queues: &[Queue] slice, but queue_msix_vector is stored separately in self.msix_queues (a Mutex<Vec<u16>>), so they can't be reused here
  directly. The bounds check logic is the same (indexing by queue_select), just against a different collection behind a lock. I could add a with_msix_queue analogue, but it seemed like overkill for two call
  sites — happy to add one if you'd prefer the symmetry.

File: virtio-devices/src/transport/pci_common_config.rs (hunk 2 above)
Comment (kaessert) [reply virtio-devices/src/transport/pci_common_config.rs]: same as above

File: virtio-devices/src/transport/pci_common_config.rs (hunk 1 above)
Comment (kaessert) [reply virtio-devices/src/transport/pci_common_config.rs]: Good suggestion on the default value — you're right that we should return the "no vector" sentinel. I used VIRTQ_MSI_NO_VECTOR (0xFFFF) rather than 0xFF since this is a u16 field.

File: virtio-devices/src/transport/pci_common_config.rs [hunk 3]
```diff
@@ -265,7 +266,11 @@ impl VirtioPciCommonConfig {
...
```
Comment (phip1611) [inline virtio-devices/src/transport/pci_common_config.rs]: very nit: I'd prefer `usize::from(self.queue_select)` which would make it more explicit the conversation (`u16` to `usize`) can never fail

File: virtio-devices/src/transport/pci_common_config.rs (hunk 1 above)
Comment (phip1611) [reply virtio-devices/src/transport/pci_common_config.rs]: fine!

**Comment by kaessert** [comment]
Thanks tons folks! 🙏

**Comment by kaessert** [comment]
To add a bit of context, i'm building a small platform to run untrusted ai agents and i'm using cloud hypervisor as the main isolation layer and i asked claude to try breaking out of it and that's how i found the bug. Pretty scary stuff if you ask me :)
