### PR TITLE
vmm: Stabilize vCPU snapshot/restore

### LINKED ISSUE #1176: ci: Fix test_snapshot_restore to support multiple vCPUs
The integration test `test_snapshot_restore` behaves inconsistently when using more than one vCPU. We need to investigate this issue and find out what's going wrong wrt the multi-vCPU support along with snapshot/restore.

### PR DESCRIPTION
**Pull request by sboeuf**
This pull request, mainly by saving all supported MSRs, fixes all the remaining issues related to vCPU snapshot/restore. Thanks to this pull request, we can now correctly snapshot and restore a VM with one or more vCPUs.

Fixes #1176

### CODE REVIEW

File: hypervisor/src/kvm/mod.rs [hunk 1]
```diff
@@ -596,15 +595,24 @@ impl cpu::Vcpu for KvmVcpu {
     /// let vcpu = vm.create_vcpu(0).unwrap();
     /// let state = vcpu.cpu_state().unwrap();
     ///
-    fn cpu_state(&self) -> cpu::Result<CpuState> {
+    fn cpu_state(&self, msr_list: &MsrList) -> cpu::Result<CpuState> {
```
Comment (sameo) [inline hypervisor/src/kvm/mod.rs:600]: I think it'd be cleaner if we could have a:

```rust
 #[cfg(target_arch = "x86_64")]
 msrs: MsrEntries,
```

in the `KvmVcpu` structure, that would cache the `MsrEntries` array creation that we do below. The list of MSRs from KVM is only created once at boot/restore so we don't need to generate the `MsrEntries` array each time we get the CPU state.
Moreover, having it as part of the `KvmCpu` structure would keep the `cpu_state` method from the `Vcpu` trait architecture agnostic.

File: hypervisor/src/kvm/mod.rs [hunk 2]
```diff
@@ -578,17 +588,16 @@ impl cpu::Vcpu for KvmVcpu {
     /// let state = vcpu.cpu_state().unwrap();
     ///
```
[the remark this answers is not in the document]
Comment (sboeuf) [reply hypervisor/src/kvm/mod.rs]: Yes I will!

File: hypervisor/src/kvm/mod.rs (hunk 1 above)
Comment (sboeuf) [reply hypervisor/src/kvm/mod.rs:600]: I can do what you're describing, but let me explain why I chose to go this way.
The list of MSRs that we want to save should be specific to the caller (`vmm` crate in this case). By implementing this as part of the `KvmCpu` would simplify the code but it would force anyone using the `hypervisor` crate to save all MSRs, which might not be what other VMM expect.
WDYT?

Comment (sameo) [reply hypervisor/src/kvm/mod.rs:600]: I understand, but is there a use case, with KVM, for not saving/restoring all the MSRs KVM supports? We've seen the side effects of trying to only use a reduced set of MSRs ;-)

If at some point we think the list of MSRs we save/restore should be VM/VMM specific, then we could extend the `Vm` trait with a `set_msr_entries(MsrEntries)` method and use the entire KVM list of MSRs by default. But until we have a use case for that, I'd suggest to keep it simple and just save/restore all MSRs.

Comment (sboeuf) [reply hypervisor/src/kvm/mod.rs:600]: Sounds good :+1:

**Comment by rbradford** [comment]
> fixes all the remaining issues related to vCPU snapshot/restore.

Love the optimism - :nerd_face:

File: hypervisor/src/kvm/mod.rs [hunk 3]
```diff
@@ -578,17 +588,16 @@ impl cpu::Vcpu for KvmVcpu {
...
     fn cpu_state(&self) -> cpu::Result<CpuState> {
-        let mut msrs = boot_msr_entries();
-        self.get_msrs(&mut msrs)?;
-
-        let vcpu_events = self.get_vcpu_events()?;
+        let mp_state = self.get_mp_state()?;
```
Comment (rbradford) [inline hypervisor/src/kvm/mod.rs:611]: In the commit message you mention that state can change as part of getting the other state. How can this happen if the vCPU is not running?

File: hypervisor/src/cpu.rs [hunk 4]
```diff
@@ -285,10 +285,16 @@ pub trait Vcpu: Send + Sync {
...
+    #[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
     ///
     /// Retrieve the current cpu states. This function is necessary to snapshot the VM
     ///
     fn cpu_state(&self) -> Result<CpuState>;
+    #[cfg(target_arch = "x86_64")]
+    ///
+    /// Retrieve the current cpu states. This function is necessary to snapshot the VM
+    ///
+    fn cpu_state(&self, msr_list: &MsrList) -> Result<CpuState>;
```
Comment (rbradford) [inline hypervisor/src/cpu.rs:297]: Would it be possible to keep the prototype the same between the architectures and have the implementation get the MSRs rather than pass it in. I think that would be nicer.

File: hypervisor/src/kvm/mod.rs (hunk 3 above)
Comment (sboeuf) [reply hypervisor/src/kvm/mod.rs:611]: The vCPU is technically "paused", but the states maintained by KVM can be changed even when the vCPU is not scheduled to run.

File: hypervisor/src/cpu.rs (hunk 4 above)
Comment (sboeuf) [reply hypervisor/src/cpu.rs:297]: I think that's what we agreed above with @sameo. I'm working on it.

File: hypervisor/src/kvm/mod.rs (hunk 3 above)
Comment (rbradford) [reply hypervisor/src/kvm/mod.rs:611]: That's a bit surprising so definitely make sure there is a comment about that.

**Comment by sboeuf** [comment]
@sameo @rbradford PR updated, PTAL!
