### PR TITLE
Fix block device resize disk

### LINKED ISSUE #7923: `/vm.resize-disk` missbehaves when VMs disk is backed by a host block device.
**Describe the bug**
When using a host block device (e.g. /dev/sdX, /dev/loopX) as the backing storage for a vm's disk, calling `/vm.resize-disk` after the external host block device has been resized does not notify the guest of the new size.

**Root cause**
`cloud-hypervisor` treats the block device as a "raw file", which seems to be classified as an unstructured file on a filesystem. When `cloud-hypervisor` tries to resize said file, it runs `ftruncate`, from which the operation errors out. Since `ftruncate` fails, the rest of the notification code path is never reached and the guest remains unaware of the resize.

**To Reproduce**
Steps to reproduce the behaviour:

Have a linux kernel ready.
<details>
<summary>
Run this script (expand to see).
</summary>

```sh
#!/bin/bash
# Reproduces: vm.resize-disk fails on block devices (ftruncate returns EINVAL)
set -eu

: "${KERNEL:?Set KERNEL=/path/to/vmlinux}"
CH="${CH_BINARY:-./target/release/cloud-hypervisor}"
SOCK="/tmp/ch-blk-resize-test.sock"
IMG="/tmp/ch-blk-resize-test.img"

cleanup() { kill $PID 2>/dev/null; losetup -d $LOOP 2>/dev/null; rm -f $IMG $SOCK; }
trap cleanup EXIT

# Create 100MB block device
truncate -s 100M $IMG
LOOP=$(losetup --find --show $IMG)

# Start VM
$CH --api-socket $SOCK --kernel $KERNEL --disk path=$LOOP,id=blk \
    --cpus boot=1 --memory size=512M --console off --serial null &
PID=$!
while [ ! -S $SOCK ]; do sleep 0.1; done
sleep 1

# Resize block device on host to 200MB
truncate -s 200M $IMG
losetup -c $LOOP

# Try to notify guest - this fails with EINVAL
echo "Host size after resize: $(blockdev --getsize64 $LOOP) bytes"
echo "Calling vm.resize-disk API..."
curl -s --unix-socket $SOCK -X PUT -H "Content-Type: application/json" \
    -d '{"id":"blk","desired_size":209715200}' \
    http://localhost/api/v1/vm.resize-disk
echo
```

</details>

Example run:
```sh
$ sudo KERNEL=<path-to-kernel>.bin ./scripts/reproduce-block-device-resize-bug.sh
cloud-hypervisor:   0.002727s: <vmm> WARN:vmm/src/device_manager.rs:2679 -- No image_type specified - detected as raw. Configuration updated to persist type across reboots and migrations.
cloud-hypervisor:   0.002756s: <vmm> WARN:vmm/src/device_manager.rs:2685 -- Autodetected raw image type. Disabling sector 0 writes.
Host size after resize: 209715200 bytes
Calling vm.resize-disk API...
["Error from API","The disk could not be resized","Error from device manager","Disk resize error","Disk resize failed","I/O error","Resize failed","Invalid argument (os error 22)"]
```

**Version**
v51.0.0

### PR DESCRIPTION
**Pull request by vincent-thomas**
As it currently is, CH doesn't support resizing disks of VMs whose storage is backed by a host block device. This PR addresses this and prevents (but doesn't fix) a deadlock of the CH process (which in turn causes VM cpu to freeze) from happening when doing so.

Previous discussion and further details: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7923

Fixes #7923

### CODE REVIEW

File: block/src/raw_async.rs [hunk 1]
```diff
@@ -68,9 +69,37 @@ impl disk_file::SparseCapable for RawFileDisk {
...
+            // Block devices cannot be resized via ftruncate - they are resized
+            // externally (LVM, losetup -c, etc.). Verify the ioctl works but
+            // don't require size to match - caller will re-query actual size.
+            let mut block_device_size: u64 = 0;
+            // SAFETY: BLKGETSIZE64 reads the device size into a u64 pointer.
+            let ret = unsafe {
+                libc::ioctl(
+                    self.file.as_raw_fd(),
+                    BLKGETSIZE64() as _,
+                    &mut block_device_size,
```
Comment (tpressure) [inline block/src/raw_async.rs]: Shouldn't we check that the block device at least has enough space for the resize operation? This should work for growing and also for shrinking the disk. If `block_device_size < size`, it's clearly a user error, isn't it?

Comment (tpressure) [reply block/src/raw_async.rs]: I didn't look at the change in block.rs. Never mind.

File: virtio-devices/src/block.rs [hunk 2]
```diff
@@ -1003,16 +1003,14 @@ impl Block {
             .resize(new_size)
             .map_err(Error::DiskResize)?;
 
-        let nsectors = new_size / SECTOR_SIZE;
-
-        self.common.pause().map_err(Error::PauseVcpus)?;
```
Comment (tpressure) [inline virtio-devices/src/block.rs:1008]: don't we need this for proper synchronization during disk-resize?

File: block/src/raw_async.rs [hunk 3]
```diff
@@ -68,9 +69,37 @@ impl disk_file::SparseCapable for RawFileDisk {
 
 impl disk_file::Resizable for RawFileDisk {
     fn resize(&mut self, size: u64) -> BlockResult<()> {
-        self.file
-            .set_len(size)
-            .map_err(|e| BlockError::new(BlockErrorKind::Io, DiskFileError::ResizeError(e)))
+        let fd_metadata = self
+            .file
+            .metadata()
+            .map_err(|e| BlockError::new(BlockErrorKind::Io, e))?;
```
Comment (weltling) [inline block/src/raw_async.rs]: The old code wrapped errors in`DiskFileError::ResizeError(e)` - this PR silently drops that and maps straight to a bare `io::Error`. Please keep the `ResizeError` wrapper on both branches so the error variant remains distinguishable in logs and upstream match arms.

Thanks

File: block/src/raw_async.rs [hunk 4]
```diff
@@ -68,9 +69,37 @@ impl disk_file::SparseCapable for RawFileDisk {
...
+        if fd_metadata.file_type().is_block_device() {
+            // Block devices cannot be resized via ftruncate - they are resized
+            // externally (LVM, losetup -c, etc.). Verify the ioctl works but
+            // don't require size to match - caller will re-query actual size.
+            let mut block_device_size: u64 = 0;
+            // SAFETY: BLKGETSIZE64 reads the device size into a u64 pointer.
+            let ret = unsafe {
+                libc::ioctl(
+                    self.file.as_raw_fd(),
+                    BLKGETSIZE64() as _,
```
Comment (weltling) [inline block/src/raw_async.rs]: Please use `query_device_size` which already handles the `BLKGETSIZE64` ioctl for block devices and `metadata()` for regular files. See the `physical_size` / `logical_size` impls in the same file. No need to duplicate the ioctl inline here.

Thanks

File: block/src/raw_async.rs [hunk 5]
```diff
@@ -68,9 +69,37 @@ impl disk_file::SparseCapable for RawFileDisk {
...
+                    BlockErrorKind::Io,
+                    io::Error::last_os_error(),
+                ));
+            }
+
+            Ok(())
+        } else {
+            self.file
+                .set_len(size)
+                .map_err(|e| BlockError::new(BlockErrorKind::Io, e))
```
Comment (weltling) [inline block/src/raw_async.rs]: Same here, please keep wrapping in `DiskFileError::ResizeError(e)`.

Thanks

File: virtio-devices/src/block.rs (hunk 2 above)
Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: Also, `PauseVcpus` is wrong here (a mistake I made). We should correct this and make it `PauseVirtioThreads` or similar.

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: pause and resume actually caused a deadlock of the `cloud-hypervisor` process and froze the whole VM indefinitely.

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: this should not happen. Does it only deadlock when you use block devices? For me, using a raw file with the original code works perfectly fine.

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: It _does not_ deadlock when using a block device on the host with "fast" I/O (for example `losetup`).
It _does_ deadlock when using a host block device on the host with "slow", network-bound I/O (for example ceph; rbd mapped block device). Both scenarios happen 100% of the time when manually testing.

The removal of the pause/resume came from experimentation, which turned out to fix this issue and work well.

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: I think we have to investigate this. IMHO, it is not ok to have the virtio-threads running while we're modifying shared atomics.

We had issues with this in the past, maybe it is something similar to this: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7881

File: block/src/raw_async.rs (hunk 3 above)
Comment (vincent-thomas) [reply block/src/raw_async.rs]: fixed.

File: block/src/raw_async.rs (hunk 5 above)
Comment (vincent-thomas) [reply block/src/raw_async.rs]: fixed.

File: block/src/raw_async.rs (hunk 4 above)
Comment (vincent-thomas) [reply block/src/raw_async.rs]: fixed.

File: virtio-devices/src/block.rs (hunk 2 above)
Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: I'll then put pause/resume back to get host block device support onto main?


> I think we have to investigate this. IMHO, it is not ok to have the virtio-threads running while we're modifying shared atomics.

I'm available to assist if that's needed/wanted.

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: Ideally, I would ask you to debug this.  If we end up in a deadlock situation, attaching gdb and do a `thread apply all bt` should give you some good pointers where the VMM is hanging.

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: @tpressure @weltling 

Pinging as this looks like a pretty serious deadlocking bug.

*Results of debugging*:

<details>

<summary>gdb results</summary>

```
(gdb) thread apply all bt

Thread 12 (LWP 1858073 "vmm"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc1c85 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::condvar::futex::Condvar::wait_optional_timeout () at library/std/src/sys/sync/condvar/futex.rs:49
#3  std::sys::sync::condvar::futex::Condvar::wait () at library/std/src/sys/sync/condvar/futex.rs:33
#4  std::sync::nonpoison::condvar::Condvar::wait<std::sync::barrier::BarrierState> () at library/std/src/sync/nonpoison/condvar.rs:126
#5  std::sync::nonpoison::condvar::Condvar::wait_while<std::sync::barrier::BarrierState, std::sync::barrier::{impl#2}::wait::{closure_env#0}> () at library/std/src/sync/nonpoison/condvar.rs:179
#6  std::sync::barrier::Barrier::wait () at library/std/src/sync/barrier.rs:128
#7  0x000057e411712153 in virtio_devices::device::{impl#1}::pause (self=0x
--Type <RET> for more, q to quit, c to continue without paging--
 (self=0x71eaa40035a8, new_size=4294967296) at virtio-devices/src/block.rs:1010
#9  0x000057e4112bc068 in vmm::device_manager::DeviceManager::resize_disk (self=0x71eaa4003038, device_id=..., new_size=4294967296) at vmm/src/device_manager.rs:5087
#10 0x000057e4114e877c in vmm::vm::Vm::resize_disk (self=0x71eaaa5fd900, id=..., desired_size=4294967296) at vmm/src/vm.rs:1984
#11 0x000057e41129f794 in vmm::{impl#13}::vm_resize_disk (self=0x71eaaa5fd900, id=..., desired_size=4294967296) at vmm/src/lib.rs:2153
#12 0x000057e41119cc7b in vmm::api::{impl#22}::request::{closure#0} (vmm=...) at vmm/src/api/mod.rs:1340
#13 0x000057e4115cc00a in core::ops::function::FnOnce::call_once<vmm::api::{impl#22}::request::{closure_env#0}, (&mut dyn vmm::api::RequestHandler)> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#14 0x000057e411231857 in alloc::boxed::{impl#31}::call_once<(&mut dyn vmm::api::RequestHandler), (dyn core::ops::function::FnOnce<(&mut dyn vmm::api::RequestHandler), Output=core::result::Result<bool, vmm::Error>> + core::marker::Send), alloc::alloc::Global> (self=..., args=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2206
#15 0x000057e41128ec05 in vmm::Vmm::control_loop (self=0x71eaaa5fd900, api_receiver=0x71eaaa5fe320) at vmm/src/lib.rs:1732
#16 0x000057e41138b9de in vmm::start_vmm_thread::{closure#0} () at vmm/src/lib.rs:572
#17 0x000057e411155fe1 in std::sys::backtrace::__rust_begin_short_backtrace<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> (f=<error reading variable: Cannot access memory at address 0xe1>) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x000057e411611d42 in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#19 0x000057e41147db30 in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), vmm::Error>, std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#20 0x000057e411397380 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>, core::result::Result<(), vmm::Error>> (data=0x71eaaa5feab0) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#21 0x000057e41161331b in __rust_try ()
#22 0x000057e411610546 in std::panicking::catch_unwind<core::result::Result<(), vmm::Error>, core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#23 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>, core::result::Result<(), vmm::Error>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#24 std::thread::lifecycle::spawn_unchecked::{closure#1}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/--Type <RET> for more, q to quit, c to continue without paging--
library/std/src/thread/lifecycle.rs:89
#25 0x000057e4115cc8cf in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<vmm::start_vmm_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#26 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#27 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#28 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#29 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 11 (LWP 1858074 "http-server"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2606 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  0x000057e4113ac9c4 in std::sync::mpmc::context::Context::wait_until (self=0x71eaaa3fa900, deadline=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/context.rs:143
#5  0x000057e4115c2114 in std::sync::mpmc::list::{impl#3}::recv::{closure#1}<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>> (cx=0x71eaaa3fa900) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/list.rs:453
#6  0x000057e4113a03cb in std::sync::mpmc::context::{impl#0}::with::{closure#0}<std::sync::mpmc::list::{impl#3}::recv::{closure_env#1}<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>, ()> (cx=0x71eaaa3fa900) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/context.rs:49
#7  std::sync::mpmc::context::{impl#0}::with::{closure#1}<std::sync::mpmc::list::{impl#3}::recv::{closure_env#1}<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>, ()> (cell=0x71eaaa3fe680) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/context.rs:57
#8  0x000057e4111bf0dc in std::thread::local::LocalKey<core::cell::Cell<core::option::Option<std::sync::mpmc::context::Context>>>::try_with<core::cell::Cell<core::option::Option<std::sync::mpmc::context::Context>>, std::sync::mpmc::context::{impl#0}::with::{closure_env#1}<std::sync::mpmc::list::{impl#3}::recv::{closure_env#1}<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>, ()>, ()> (self=0x57e411d1afa8, f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/local.rs:513
#9  0x000057e41139f494 in std::sync::mpmc::context::Context::with<std::sync::mpmc::list::{impl#3}::recv::{closure_env#1}<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/context.rs:53
#10 0x000057e4115c1f96 in std::sync::mpmc::list::Channel<core::result::Result<vmm::api::ApiResponsePayload, v--Type <RET> for more, q to quit, c to continue without paging--
mm::api::ApiError>>::recv<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>> (self=0x71ea9c004e80, deadline=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/list.rs:442
#11 0x000057e4113bbd12 in std::sync::mpmc::Receiver<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>::recv<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>> (self=0x71eaaa3fae60) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpmc/mod.rs:985
#12 0x000057e4111b67e7 in std::sync::mpsc::Receiver<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>>::recv<core::result::Result<vmm::api::ApiResponsePayload, vmm::api::ApiError>> (self=0x71eaaa3fae60) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sync/mpsc.rs:849
#13 0x000057e4111831b3 in vmm::api::get_response<vmm::api::VmResizeDisk> (action=0x1, api_evt=..., api_sender=..., data=...) at vmm/src/api/mod.rs:537
#14 0x000057e4111914f4 in vmm::api::get_response_body<vmm::api::VmResizeDisk> (action=0x1, api_evt=..., api_sender=..., data=...) at vmm/src/api/mod.rs:546
#15 0x000057e41114e80b in vmm::api::{impl#22}::send (self=0x1, api_evt=..., api_sender=..., data=...) at vmm/src/api/mod.rs:1358
#16 0x000057e41115353a in vmm::api::http::http_endpoint::{impl#49}::handle_request (self=0x1, api_notifier=..., api_sender=..., body=0x71eaaa3fc5b8, _files=...) at vmm/src/api/http/http_endpoint.rs:393
#17 0x000057e41150b4ac in vmm::api::http::http_endpoint::{impl#9}::put_handler (self=0x71ea9c003b80, api_notifier=..., api_sender=..., body=0x71eaaa3fc5b8, files=...) at vmm/src/api/http/http_endpoint.rs:538
#18 0x000057e4112bb247 in vmm::api::http::EndpointHandler::handle_request<vmm::api::http::http_endpoint::VmActionHandler> (self=0x71ea9c003b80, req=0x71eaaa3fc580, api_notifier=..., api_sender=...) at vmm/src/api/http/mod.rs:121
#19 0x000057e4114e4f46 in vmm::api::http::handle_http_request (request=0x71eaaa3fc580, api_notifier=0x71eaaa3fc958, api_sender=0x71eaaa3fc900) at vmm/src/api/http/mod.rs:309
#20 0x000057e41115c0bf in vmm::api::http::start_http_thread::{closure#0}::{closure#2}::{closure#0} (request=0x71eaaa3fc580) at vmm/src/api/http/mod.rs:376
#21 0x000057e411485907 in micro_http::server::ServerRequest::process<vmm::api::http::start_http_thread::{closure#0}::{closure#2}::{closure_env#0}> (self=0x71eaaa3fc580, callable=...) at /home/ubuntu/.cargo/git/checkouts/micro-http-b6958a74e1f08106/5c2254d/src/server.rs:56
#22 0x000057e41115b89e in vmm::api::http::start_http_thread::{closure#0}::{closure#2} () at vmm/src/api/http/mod.rs:375
#23 0x000057e4115cf07e in core::ops::function::FnOnce::call_once<vmm::api::http::start_http_thread::{closure#0}::{closure_env#2}, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e41147dbd1 in core::panic::unwind_safe::{impl#23}::call_once<(), vmm::api::http::start_http_thread::{closure#0}::{closure_env#2}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#25 0x000057e4113976c7 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<vmm::api::http::start_http_thread::{closure#0}::{closure_env#2}>, ()> (data=0x71eaaa3fca20) at /nix/store/2rq94--Type <RET> for more, q to quit, c to continue without paging--
3s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#26 0x000057e4114bc6bb in __rust_try ()
#27 0x000057e4114bc63c in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<vmm::api::http::start_http_thread::{closure#0}::{closure_env#2}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#28 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<vmm::api::http::start_http_thread::{closure#0}::{closure_env#2}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#29 0x000057e41115acdb in vmm::api::http::start_http_thread::{closure#0} () at vmm/src/api/http/mod.rs:369
#30 0x000057e411155f71 in std::sys::backtrace::__rust_begin_short_backtrace<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> (f=<error reading variable: Cannot access memory at address 0xf1>) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#31 0x000057e411612822 in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#32 0x000057e41147dcf0 in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), vmm::Error>, std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#33 0x000057e411397780 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>, core::result::Result<(), vmm::Error>> (data=0x71eaaa3fdab0) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#34 0x000057e41161331b in __rust_try ()
#35 0x000057e41160ee96 in std::panicking::catch_unwind<core::result::Result<(), vmm::Error>, core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#36 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>>, core::result::Result<(), vmm::Error>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#37 std::thread::lifecycle::spawn_unchecked::{closure#1}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#38 0x000057e4115cc8af in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<vmm::api::http::start_http_thread::{closure_env#0}, core::result::Result<(), vmm::Error>>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
--Type <RET> for more, q to quit, c to continue without paging--
#39 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#40 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#41 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#42 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 10 (LWP 1858075 "vmm_signal_hand"):
#0  0x000071eaaa72bc4a in recv () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411ce0722 in std::sys::net::connection::socket::unix::Socket::recv_with_flags () at library/std/src/sys/net/connection/socket/unix.rs:289
#2  std::sys::net::connection::socket::unix::Socket::read () at library/std/src/sys/net/connection/socket/unix.rs:304
#3  std::os::unix::net::stream::{impl#4}::read () at library/std/src/os/unix/net/stream.rs:637
#4  std::os::unix::net::stream::{impl#3}::read () at library/std/src/os/unix/net/stream.rs:617
#5  0x000057e4115998f2 in signal_hook::iterator::SignalsInfo<signal_hook::iterator::exfiltrator::SignalOnly>::has_signals<signal_hook::iterator::exfiltrator::SignalOnly> (read=0x71eaaa1fc000) at /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/signal-hook-0.4.3/src/iterator/mod.rs:185
#6  0x000057e4115cb9c0 in core::ops::function::FnMut::call_mut<fn(&mut std::os::unix::net::stream::UnixStream) -> core::result::Result<bool, std::io::error::Error>, (&mut std::os::unix::net::stream::UnixStream)> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:166
#7  0x000057e4115a5240 in signal_hook::iterator::backend::SignalDelivery<std::os::unix::net::stream::UnixStream, signal_hook::iterator::exfiltrator::SignalOnly>::poll_pending<std::os::unix::net::stream::UnixStream, signal_hook::iterator::exfiltrator::SignalOnly, fn(&mut std::os::unix::net::stream::UnixStream) -> core::result::Result<bool, std::io::error::Error>> (self=0x71eaaa1fbfd0, has_signals=0x71eaaa1fbd17) at /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/signal-hook-0.4.3/src/iterator/backend.rs:357
#8  0x000057e4115a5935 in signal_hook::iterator::backend::SignalIterator<&mut signal_hook::iterator::backend::SignalDelivery<std::os::unix::net::stream::UnixStream, signal_hook::iterator::exfiltrator::SignalOnly>, signal_hook::iterator::exfiltrator::SignalOnly>::poll_signal<&mut signal_hook::iterator::backend::SignalDelivery<std::os::unix::net::stream::UnixStream, signal_hook::iterator::exfiltrator::SignalOnly>, signal_hook::iterator::exfiltrator::SignalOnly, std::os::unix::net::stream::UnixStream, fn(&mut std::os::unix::net::stream::UnixStream) -> core::result::Result<bool, std::io::error::Error>> (self=0x71eaaa1fbe90, has_signals=0x71eaaa1fbd17) at /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/signal-hook-0.4.3/src/iterator/backend.rs:465
#9  0x000057e411599e49 in signal_hook::iterator::{impl#3}::next<signal_hook::iterator::exfiltrator::SignalOnly> (self=0x71eaaa1fbe90) at /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/signal-hook-0.4.3/src/iterator/mod.rs:305
#10 0x000057e411291f1c in vmm::Vmm::signal_handler (signals=..., original_termios_opt=0x71eaa4000cb0, exit_evt=0x71eaaa1fc778) at vmm/src/lib.rs:742
#11 0x000057e41139284e in vmm::{impl#12}::setup_signal_handler::{closure#0}::{closure#1} () at vmm/src/lib.rs:809
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x000057e41147da30 in core::panic::unwind_safe::{impl#23}::call_once<(), vmm::{impl#12}::setup_signal_handler::{closure#0}::{closure_env#1}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#13 0x000057e4113974ab in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<vmm::{impl#12}::setup_signal_handler::{closure#0}::{closure_env#1}>, ()> (data=0x71eaaa1fc138) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#14 0x000057e4114bc6bb in __rust_try ()
#15 0x000057e4114bc1cc in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<vmm::{impl#12}::setup_signal_handler::{closure#0}::{closure_env#1}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#16 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<vmm::{impl#12}::setup_signal_handler::{closure#0}::{closure_env#1}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#17 0x000057e411391f27 in vmm::{impl#12}::setup_signal_handler::{closure#0} () at vmm/src/lib.rs:808
#18 0x000057e411155fc6 in std::sys::backtrace::__rust_begin_short_backtrace<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()> (f=<error reading variable: Cannot access memory at address 0x11>) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#19 0x000057e4116117ff in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#20 0x000057e41147db64 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#21 0x000057e4113979d0 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()>>, ()> (data=0x71eaaa1fcbc8) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#22 0x000057e41161331b in __rust_try ()
#23 0x000057e41160fb14 in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#24 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#25 std::thread::lifecycle::spawn_unchecked::{closure#1}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#26 0x000057e4115cc51f in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<vmm::{impl#12}::setup_signal_handler::{closure_env#0}, ()>, ()> () at /nix/store/2rq943s2w9y0ayl--Type <RET> for more, q to quit, c to continue without paging--
a43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#27 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#28 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#29 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#30 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 9 (LWP 1858210 "vcpu0"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e41149d7f0 in vmm::cpu::{impl#6}::start_vcpu::{closure#1}::{closure#0} () at vmm/src/cpu.rs:1364
#6  0x000057e4113976f6 in std::panicking::catch_unwind::do_call<vmm::cpu::{impl#6}::start_vcpu::{closure#1}::{closure_env#0}, ()> (data=0x71eaa9bf84b0) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#7  0x000057e4114bc6bb in __rust_try ()
#8  0x000057e4114bc3cc in std::panicking::catch_unwind<(), vmm::cpu::{impl#6}::start_vcpu::{closure#1}::{closure_env#0}> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#9  std::panic::catch_unwind<vmm::cpu::{impl#6}::start_vcpu::{closure#1}::{closure_env#0}, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#10 0x000057e41149c74a in vmm::cpu::{impl#6}::start_vcpu::{closure#1} () at vmm/src/cpu.rs:1320
#11 0x000057e411155fa6 in std::sys::backtrace::__rust_begin_short_backtrace<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#12 0x000057e411611acf in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#13 0x000057e41147dab4 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#14 0x000057e411397474 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()>>, ()> (data=0x71eaa9bf99a0) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#15 0x000057e41161331b in __rust_try ()
--Type <RET> for more, q to quit, c to continue without paging--
#16 0x000057e41160f226 in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#17 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#18 std::thread::lifecycle::spawn_unchecked::{closure#1}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#19 0x000057e4115cc2df in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<vmm::cpu::{impl#6}::start_vcpu::{closure_env#1}, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#20 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#21 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#22 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#23 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 8 (LWP 1858211 "kvm-nx-lpage-re"):
#0  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x0

Thread 7 (LWP 1858240 "__rng"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e411811629 in virtio_devices::epoll_helper::EpollHelper::run_with_timeout (self=0x71eaa99f79b8, paused=0x71eaa400a850, paused_sync=0x71eaa400d990, handler=..., timeout=-1, enable_event_list=false) at virtio-devices/src/epoll_helper.rs:232
#6  0x000057e411811d6c in virtio_devices::epoll_helper::EpollHelper::run (self=0x71eaa99f79b8, paused=0x71eaa400a850, paused_sync=0x71eaa400d990, handler=...) at virtio-devices/src/epoll_helper.rs:160
#7  0x000057e411725359 in virtio_devices::rng::RngEpollHandler::run (self=0x71eaa99f7c30, paused=0x71eaa400a850, paused_sync=0x71eaa400d990) at virtio-devices/src/rng.rs:112
#8  0x000057e411812a8a in virtio_devices::rng::{impl#4}::activate::{closure#1} () at virtio-devices/src/rng.rs:285
#9  0x000057e41181819f in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), virtio_devi--Type <RET> for more, q to quit, c to continue without paging--
ces::epoll_helper::EpollHelperError>, virtio_devices::rng::{impl#4}::activate::{closure_env#1}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#10 0x000057e411762430 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (data=0x71eaa99f7dc8) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#11 0x000057e41176218b in __rust_try ()
#12 0x000057e411761439 in std::panicking::catch_unwind<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#13 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#14 0x000057e41175c343 in virtio_devices::thread_helper::spawn_virtio_thread::{closure#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}> () at virtio-devices/src/thread_helper.rs:47
#15 0x000057e4117e29c7 in std::sys::backtrace::__rust_begin_short_backtrace<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#16 0x000057e4117e13fc in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#17 0x000057e4118182b4 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#18 0x000057e4117633e4 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()>>, ()> (data=0x71eaa99f8af0) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#19 0x000057e4117e284b in __rust_try ()
#20 0x000057e4117e030a in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#21 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_d--Type <RET> for more, q to quit, c to continue without paging--
evices::rng::{impl#4}::activate::{closure_env#1}>, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#22 std::thread::lifecycle::spawn_unchecked::{closure#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#23 0x000057e4116e2aaf in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::rng::{impl#4}::activate::{closure_env#1}>, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#25 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#26 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#27 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 6 (LWP 1858241 "_disk0_q0"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e411811629 in virtio_devices::epoll_helper::EpollHelper::run_with_timeout (self=0x71eaa97f5808, paused=0x71eaa402dd70, paused_sync=0x71eaa400cf80, handler=..., timeout=-1, enable_event_list=false) at virtio-devices/src/epoll_helper.rs:232
#6  0x000057e411811d6c in virtio_devices::epoll_helper::EpollHelper::run (self=0x71eaa97f5808, paused=0x71eaa402dd70, paused_sync=0x71eaa400cf80, handler=...) at virtio-devices/src/epoll_helper.rs:160
#7  0x000057e4116bd42c in virtio_devices::block::BlockEpollHandler::run (self=0x71eaa97f5b60, paused=0x71eaa402dd70, paused_sync=0x71eaa400cf80) at virtio-devices/src/block.rs:627
#8  0x000057e4117f05e6 in virtio_devices::block::{impl#5}::activate::{closure#2} () at virtio-devices/src/block.rs:1160
#9  0x000057e41181835f in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, virtio_devices::block::{impl#5}::activate::{closure_env#2}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#10 0x000057e411762bb0 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (data=0x71eaa97f5ec8) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#11 0x000057e41176218b in __rust_try ()
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x000057e411761129 in std::panicking::catch_unwind<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::block::{impl#5}::activate::{closure_env#2}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#13 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#14 0x000057e4117565a5 in virtio_devices::thread_helper::spawn_virtio_thread::{closure#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}> () at virtio-devices/src/thread_helper.rs:47
#15 0x000057e4117e28c7 in std::sys::backtrace::__rust_begin_short_backtrace<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#16 0x000057e4117e1d1c in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#17 0x000057e411818284 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#18 0x000057e4117623e4 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()>>, ()> (data=0x71eaa97f7850) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#19 0x000057e4117e284b in __rust_try ()
#20 0x000057e4117dfa4a in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#21 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#22 std::thread::lifecycle::spawn_unchecked::{closure#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#23 0x000057e4116e26bf in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::block::{impl#5}::activate::{closure_env#2}>, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/r--Type <RET> for more, q to quit, c to continue without paging--
ustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#25 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#26 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#27 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 5 (LWP 1858242 "_net1_ctrl"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e411811629 in virtio_devices::epoll_helper::EpollHelper::run_with_timeout (self=0x71eaa95f57f8, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0, handler=..., timeout=-1, enable_event_list=false) at virtio-devices/src/epoll_helper.rs:232
#6  0x000057e411811d6c in virtio_devices::epoll_helper::EpollHelper::run (self=0x71eaa95f57f8, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0, handler=...) at virtio-devices/src/epoll_helper.rs:160
#7  0x000057e411732099 in virtio_devices::net::NetCtrlEpollHandler::run_ctrl (self=0x71eaa95f5a48, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0) at virtio-devices/src/net.rs:83
#8  0x000057e411724374 in virtio_devices::net::{impl#6}::activate::{closure#0} () at virtio-devices/src/net.rs:792
#9  0x000057e4118180ed in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, virtio_devices::net::{impl#6}::activate::{closure_env#0}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#10 0x000057e411762231 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (data=0x71eaa95f5c20) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#11 0x000057e41176218b in __rust_try ()
#12 0x000057e4117612b8 in std::panicking::catch_unwind<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#0}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#13 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#14 0x000057e411752ba5 in virtio_devices::thread_helper::spawn_virtio_thread::{closure#0}<virtio_devices::net--Type <RET> for more, q to quit, c to continue without paging--
::{impl#6}::activate::{closure_env#0}> () at virtio-devices/src/thread_helper.rs:47
#15 0x000057e4117e2947 in std::sys::backtrace::__rust_begin_short_backtrace<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#16 0x000057e4117e0b7c in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#17 0x000057e411818474 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#18 0x000057e4117623a0 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()>>, ()> (data=0x71eaa95f6aa8) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#19 0x000057e4117e284b in __rust_try ()
#20 0x000057e4117ddcea in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#21 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#22 std::thread::lifecycle::spawn_unchecked::{closure#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#23 0x000057e4116e270f in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#0}>, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#25 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#26 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#27 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 4 (LWP 1858243 "_net1_qp0"):
--Type <RET> for more, q to quit, c to continue without paging--
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e411811629 in virtio_devices::epoll_helper::EpollHelper::run_with_timeout (self=0x71eaa9df6cf8, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0, handler=..., timeout=-1, enable_event_list=false) at virtio-devices/src/epoll_helper.rs:232
#6  0x000057e411811d6c in virtio_devices::epoll_helper::EpollHelper::run (self=0x71eaa9df6cf8, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0, handler=...) at virtio-devices/src/epoll_helper.rs:160
#7  0x000057e411731cab in virtio_devices::net::NetEpollHandler::run (self=0x71eaa9df7318, paused=0x71eaa4022790, paused_sync=0x71eaa40373b0) at virtio-devices/src/net.rs:345
#8  0x000057e411724696 in virtio_devices::net::{impl#6}::activate::{closure#2} () at virtio-devices/src/net.rs:871
#9  0x000057e4118181dd in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, virtio_devices::net::{impl#6}::activate::{closure_env#2}> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#10 0x000057e411762cb1 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (data=0x71eaa9df7910) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#11 0x000057e41176218b in __rust_try ()
#12 0x000057e4117618c8 in std::panicking::catch_unwind<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#2}>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#13 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#14 0x000057e411757266 in virtio_devices::thread_helper::spawn_virtio_thread::{closure#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}> () at virtio-devices/src/thread_helper.rs:47
#15 0x000057e4117e2a37 in std::sys::backtrace::__rust_begin_short_backtrace<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#16 0x000057e4117e051f in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/threa--Type <RET> for more, q to quit, c to continue without paging--c
d/lifecycle.rs:91
#17 0x000057e411818074 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#18 0x000057e411762960 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()>>, ()> (data=0x71eaa9dfa478) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#19 0x000057e4117e284b in __rust_try ()
#20 0x000057e4117df005 in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#21 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#22 std::thread::lifecycle::spawn_unchecked::{closure#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#23 0x000057e4116e272f in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::net::{impl#6}::activate::{closure_env#2}>, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#25 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#26 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#27 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 3 (LWP 1858244 "vsock0"):
#0  0x000071eaaa72728d in syscall () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000057e411cc2e57 in std::sys::pal::unix::futex::futex_wait () at library/std/src/sys/pal/unix/futex.rs:73
#2  std::sys::sync::thread_parking::futex::Parker::park () at library/std/src/sys/sync/thread_parking/futex.rs:55
#3  std::thread::thread::Thread::park () at library/std/src/thread/thread.rs:121
#4  std::thread::functions::park () at library/std/src/thread/functions.rs:529
#5  0x000057e411811629 in virtio_devices::epoll_helper::EpollHelper::run_with_timeout (self=0x71eaa9ffa758, paused=0x71eaa4013af0, paused_sync=0x71eaa4031380, handler=..., timeout=-1, enable_event_list=false) at virtio-devices/src/epoll_helper.rs:232
#6  0x000057e411811d6c in virtio_devices::epoll_helper::EpollHelper::run (self=0x71eaa9ffa758, paused=0x71eaa4013af0, paused_sync=0x71eaa4031380, handler=...) at virtio-devices/src/epoll_helper.rs:160
#7  0x000057e411606c25 in virtio_devices::vsock::device::VsockEpollHandler<virtio_devices::vsock::unix::muxer::VsockMuxer>::run<virtio_devices::vsock::unix::muxer::VsockMuxer> (self=0x71eaa9ffab88, paused=0x71eaa4013af0, paused_sync=0x71eaa4031380) at virtio-devices/src/vsock/device.rs:221
#8  0x000057e411601be4 in virtio_devices::vsock::device::{impl#4}::activate::{closure#0}<virtio_devices::vsock::unix::muxer::VsockMuxer> () at virtio-devices/src/vsock/device.rs:476
#9  0x000057e41147dc3e in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#10 0x000057e4113975b1 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (data=0x71eaa9ffad40) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#11 0x000057e4114bc6bb in __rust_try ()
#12 0x000057e4114bc058 in std::panicking::catch_unwind<core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>, core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#13 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, core::result::Result<(), virtio_devices::epoll_helper::EpollHelperError>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#14 0x000057e41125828c in virtio_devices::thread_helper::spawn_virtio_thread::{closure#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>> () at virtio-devices/src/thread_helper.rs:47
#15 0x000057e411155eb7 in std::sys::backtrace::__rust_begin_short_backtrace<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166
#16 0x000057e411612b5c in std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91
#17 0x000057e41147da84 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274
#18 0x000057e411397990 in std::panicking::catch_unwind::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()>>, ()> (data=0x71eaa9ffbad8) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:581
#19 0x000057e41161331b in __rust_try ()
#20 0x000057e41161025a in std::panicking::catch_unwind<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()>>> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panicking.rs:544
#21 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked::{closure#1}::{closure_env#0}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()>>, ()> (f=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/panic.rs:359
#22 std::thread::lifecycle::spawn_unchecked::{closure#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89
#23 0x000057e4115cbd2f in core::ops::function::FnOnce::call_once<std::thread::lifecycle::spawn_unchecked::{closure_env#1}<virtio_devices::thread_helper::spawn_virtio_thread::{closure_env#0}<virtio_devices::vsock::device::{impl#4}::activate::{closure_env#0}<virtio_devices::vsock::unix::muxer::VsockMuxer>>, ()>, ()> () at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#24 0x000057e411cbf69f in alloc::boxed::{impl#31}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2206
#25 std::sys::thread::unix::{impl#2}::new::thread_start () at library/std/src/sys/thread/unix.rs:130
#26 0x000071eaaa69caa4 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#27 0x000071eaaa729c6c in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (LWP 1858245 "iou-wrk-1858241"):
#0  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x0

Thread 1 (LWP 1858072 "cloud-hyperviso"):
#0  0x000071eaaa698d71 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x000071eaaa69e7a3 in ?? () from target:/lib/x86_64-linux-gnu/libc.so.6
#2  0x000057e411cbf951 in std::sys::thread::unix::Thread::join () at library/std/src/sys/thread/unix.rs:138
#3  0x000057e41161302e in std::thread::lifecycle::JoinInner<core::result::Result<(), vmm::Error>>::join<core::result::Result<(), vmm::Error>> (self=<error reading variable: Cannot access memory at address 0x109>) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:241
#4  0x000057e4115ab001 in std::thread::join_handle::JoinHandle<core::result::Result<(), vmm::Error>>::join<core::result::Result<(), vmm::Error>> (self=...) at /nix/store/2rq943s2w9y0ayla43b87wfgbm8qydyv-rust-stable/lib/rustlib/src/rust/library/std/src/thread/join_handle.rs:148
#5  0x000057e4110f8d02 in cloud_hypervisor::start_vmm (cmd_arguments=0x7fffbb5d4ad0) at cloud-hypervisor/src/main.rs:788
#6  0x000057e4110f591f in cloud_hypervisor::main () at cloud-hypervisor/src/main.rs:907
(gdb)
```

</details>

<details>

<summary>Root cause found by AI (opus 4.5)</summary>

```
  The VM is already paused when resize_disk is called, causing VirtioCommon::pause() to
  deadlock.

  Deadlock Mechanism

  1. Initial state: The VM is paused (via a prior vm.pause() API call or similar). All
  virtio device threads are parked at epoll_helper.rs:232 inside the pause handler:
  while paused.load(Ordering::SeqCst) {
      thread::park();  // Line 232 - threads are stuck here
  }
  2. API call: resize_disk is called while the VM is paused
  3. Block::resize() at block.rs:1010 calls self.common.pause()
  4. VirtioCommon::pause() at device.rs:324-344:
    - Sets paused = true (already true, no effect)
    - Writes to pause_evt (but threads are parked, not watching epoll)
    - Calls paused_sync.wait() - waits for worker threads to reach the barrier
  5. Deadlock: The worker threads are parked (not watching epoll), so they never wake up to
   process the PAUSE_EVENT and reach the barrier. The VMM thread waits forever.

  Evidence from Backtrace

  - Thread 12 (vmm): Blocked on Barrier::wait() in VirtioCommon::pause() called from
  Block::resize()
  - Thread 6 (_disk0_q0): Parked at epoll_helper.rs:232 - inside the pause handler's park
  loop
  - All other virtio threads (__rng, _net1_ctrl, _net1_qp0, vsock0): Also parked at line
  232
  - Thread 9 (vcpu0): Parked at cpu.rs:1364 - the vCPU pause loop

  This confirms the entire VM was paused before resize_disk was called.

  The Bug

  VirtioCommon::pause() at device.rs:324 does not check if the device is already paused
  before attempting to synchronize with worker threads via the barrier. When called on an
  already-paused device, it deadlocks because the threads are parked and won't reach the
  barrier.

  Code Location

  The problematic code is in virtio-devices/src/device.rs:323-344:
  fn pause(&mut self) -> std::result::Result<(), MigratableError> {
      self.paused.store(true, Ordering::SeqCst);
      if let Some(pause_evt) = &self.pause_evt {
          pause_evt.write(1)?;
          self.paused_sync.as_ref().unwrap().wait();  // <-- DEADLOCKS if already paused
      }
      Ok(())
  }
```

</details>

Comment (phip1611) [reply virtio-devices/src/block.rs:1008]: Nice debugging, thanks! Generally, pause() and resume() in CHV are not (yet) idempotent. I think calling pause() multiple times should be fine, so

```rust
let old = self.paused.swap(true, Ordering::SeqCst);
if old {
   return
}
/* normal pause code */
```

should be a viable fix 🤔

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: The question is: was your VM really in paused state when you ran your test @vincent-thomas ? From the previous description, I would rather have assumed that you had the VM running while you performed the disk resize? Did you pause it explicitly?

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: @phip1611 I've added a fix patch already (side-affect: this makes `/vm.pause` idempotent btw): https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7948/commits/603b73b3d48d7ff845f2abee5c18a597278ee1e9

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: > The question is: was your VM really in paused state when you ran your test @vincent-thomas ?

For the loopback block device reproducible script? No. I did for the rbd block device test.

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: > Nice debugging, thanks! Generally, pause() and resume() in CHV are not (yet) idempotent. I think calling pause() multiple times should be fine, so
> 
> ```rust
> let old = self.paused.swap(true, Ordering::SeqCst);
> if !old {
>    return
> }
> /* normal pausing code */
> ```
> 
> should be a viable fix 🤔

Your suggestion is incorrect. If the VM was in running state before, it will be in paused state afterwards. 
Or am I missing something?

Comment (phip1611) [reply virtio-devices/src/block.rs:1008]: Update: sorry I was following a wrong thought; discussion was misleading. I've  marked the messages above as `outdated` - Thanks Thomas!

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: But even then, we would pause the VM if it was running before. Wouldn´t we? It is `swap`, not compare-exchange.

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: If the VM was paused, and we can ensure that it says paused during the resize call, I would suggest that we only then skip pausing/resuming the virtio-queues. @phip1611 @vincent-thomas

Comment (tpressure) [reply virtio-devices/src/block.rs:1008]: @phip1611 you mix up vcpu pausing and virtqueu pausing ;)

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: @tpressure @phip1611 Have a look at my recently updated diff, It is changed to fix the root cause.

Comment (phip1611) [reply virtio-devices/src/block.rs:1008]: > only then skip pausing/resuming the virtio-queues.

I agree - looks like @vincent-thomas did the right thing now. LGTM on a first glance

Comment (vincent-thomas) [reply virtio-devices/src/block.rs:1008]: I'll ask for another review since it sounds like this conversation has cleared up maintainers worries.

**Comment by phip1611** [comment]
please fix CI

File: block/src/raw_async.rs [hunk 6]
```diff
@@ -72,33 +72,26 @@ impl disk_file::Resizable for RawFileDisk {
...
-            // SAFETY: BLKGETSIZE64 reads the device size into a u64 pointer.
-            let ret = unsafe {
-                libc::ioctl(
-                    self.file.as_raw_fd(),
-                    BLKGETSIZE64() as _,
-                    &mut block_device_size,
-                )
-            };
-            if ret != 0 {
+            // externally (LVM, losetup -c, etc.). Verify the size matches.
```
Comment (phip1611) [inline block/src/raw_async.rs:79]: in commit message

> Previously running pause when already paused would wait for threads
that were already parked, which caused a deadlock, see:

Please add a sentence how you can end up in that situation or how likely it is

**Review by phip1611 — CHANGES_REQUESTED** [review]
The changes are good, thanks!

It looks to me that your second commit changes lines you introduced in the first commit. We value clean git histories.

Please bring your commits into clean structure, then we can move this forward.

Also see https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/CONTRIBUTING.md#patch-format--git-commit-hygiene

File: block/src/raw_async.rs (hunk 6 above)
Comment (vincent-thomas) [reply block/src/raw_async.rs:79]: I think it's up to standards now.

**Comment by vincent-thomas** [comment]
> Please bring your commits into clean structure

Sorry about that, should be okay now.

**Comment by phip1611** [comment]
Please run `cargo +nightly fmt --all` to fix your formatting.

The commit message check can be ignored (optional CI step). You could properly fix it by using the scheme:

```
See [0].

[0] https://...
```

File: virtio-devices/src/device.rs [hunk 7]
```diff
@@ -326,7 +326,13 @@ impl Pausable for VirtioCommon {
             "Pausing virtio-{}",
             VirtioDeviceType::from(self.device_type)
         );
-        self.paused.store(true, Ordering::SeqCst);
+
+        // If already paused, return early to avoid deadlock waiting on barrier
```
Comment (phip1611) [inline virtio-devices/src/device.rs:344]: > This situation occurs when the VMM thread holds a device mutex while
calling an operation that triggers pause(), and a vCPU thread
simultaneously needs that same mutex for MMIO access. With slow I/O
backends (like RBD/Ceph), the timing window for this race is larger,
making the deadlock more likely to occur.

Ah, wait. Doesn't this open another race window? Another thread may unpause this too early? Or are we protected by mutexes?

**Comment by vincent-thomas** [comment]
> Your race commit fix deserves its own PR as I think it is independent of the resize fix?

Yeah sure but if the resize fix lands and the race commit doesn't, then CH will deadlock on any resize-disk API call where:
- VM has been paused before the resize disk call.
- The VM is backed by a slow host block device.

**Comment by rbradford** [comment]
The ordering of the commits in the PR is probably wrong then - but I asked you to split the race fix out as it's an obviously good fix.

**Comment by rbradford** [comment]
I flipped the order of your commits.

File: virtio-devices/src/device.rs (hunk 7 above)
Comment (rbradford) [reply virtio-devices/src/device.rs:344]: Maybe this is another place where we need a three-way handshake with atomic

RUNNING -> PAUSING -> PAUSED

It might not strictly needed in this case since we don't really do anything after.

**Review by rbradford — CHANGES_REQUESTED** [review]
Still need cargo fmt

**Comment by vincent-thomas** [comment]
> Still need cargo fmt

Sorry about this, ran it a couple of times I thought.... Should be fixed now.
