### PR TITLE
pci/vmm: Harden BAR reprogramming against out-of-range MMIO addresses

### LINKED ISSUE #7938: VMM crashes when guest programs BAR to unallocatable MMIO address
**Describe the bug**

While debugging Windows virtio-win 0.1.285 NetKVM driver issues (#7925), we observed a scenario where the guest programs a PCI BAR to an address that falls outside the MMIO64 allocator range. This causes `move_bar` to fail, but the BAR config register has already been updated by `detect_bar_reprogramming()`. The resulting inconsistency between config space and the MMIO bus mapping leads to virtio device activation failure (`Number of enabled queues lower than min`), crashing the VMM.

In our case, the trigger was a driver bug (wrong `used_len` in ctrl_queue response caused the driver to reset and attempt BAR reprogramming to a high address). After fixing the driver-side issue, this crash path is no longer hit. However, the underlying VMM behavior — crashing on a failed BAR move — seems worth hardening regardless of the trigger.

There are two independent issues:

**1. BAR config register not rolled back on failed move**

`detect_bar_reprogramming()` in `pci/src/configuration.rs` updates `bars[].addr` before `move_bar` is called. When `move_bar` fails (e.g., address outside allocator range), the config register says the BAR is at the new address, but the MMIO bus mapping is still at the old address. The guest reads back the new address, assumes it worked, and configures queues accordingly — but the device backend is at the old address. This causes queue setup to partially fail, and `activate()` rejects the device.

**2. MMIO64 allocator loses ~4 GiB at top of address space**

`create_mmio_allocators()` computes segment size as `(range / alignment) * alignment`, which truncates up to one alignment unit (4 GiB with 4 GiB alignment). Addresses near the top of the physical address space fall in this gap and cannot be allocated. While this didn't cause our issue directly (it was the driver bug), it's a latent issue for hosts with 46-bit physical addressing where the gap is at ~64 TiB.

**Error log (before fix):**

```
WARN: Failed moving device BAR: failed allocating new MMIO range: 0x3fffffd80000->0x3fffffe00000(0x80000)
ERROR: Number of enabled queues lower than min: 1 vs 2
Fatal error: VmmThread(ActivateVirtioDevices(...))
```

**Version**

```
cloud-hypervisor v51.0.0 (main branch)
```

**VM configuration**

```
cloud-hypervisor \
  --kernel CLOUDHV.fd \
  --disk path=windows.qcow2,num_queues=2,queue_size=512 \
  --cpus boot=2,kvm_hyperv=on \
  --memory size=4G \
  --net tap=tap0,mac=52:54:00:12:34:56,num_queues=2 \
  --serial tty --console off
```

Guest: Windows 11 25H2, virtio-win 0.1.285
Host: Linux 6.17, 46-bit physical addressing

**Defensive fixes**

We have two commits that harden the VMM against this class of failures. We're not sure if upstream considers this worth merging since the original trigger was a driver issue, but sharing in case it's useful:

Branch: https://github.com/CMGS/cloud-hypervisor/tree/fix/bar-rollback-defensive

1. **pci: rollback BAR address on failed move_bar** — restores config register and bar_regions to old values when `move_bar` fails, keeping device state consistent with MMIO mapping
2. **vmm: extend last MMIO64 allocator to cover full range** — gives the last PCI segment allocator all remaining space up to end of device area, eliminating the alignment truncation gap

**Logs**

N/A — the crash is deterministic when triggered.

### PR DESCRIPTION
**Pull request by CMGS**
## Summary

When a guest programs a PCI BAR to an address outside the allocatable MMIO range, `move_bar` fails but the config register has already been updated.
This inconsistency between config space and the MMIO bus mapping causes virtio device activation failure, crashing the VMM.

This PR adds two defensive fixes:

- **pci: rollback BAR address on failed move_bar** — restores config registers and `bar_regions` to old values when `move_bar` fails, keeping the device functional at its original address.
- **vmm: extend last MMIO64 allocator to cover full range** — gives the last PCI segment allocator all remaining space up to the end of the device area, eliminating the alignment truncation gap (~4 GiB) at the top of the address space.

Fixes #7938

### CODE REVIEW

File: virtio-devices/src/transport/pci_device.rs [hunk 1]
```diff
@@ -1133,6 +1133,17 @@ impl PciDevice for VirtioPciDevice {
         Ok(())
     }
 
+    fn restore_bar_addr(&mut self, params: &BarReprogrammingParams) {
+        // Undo move_bar's bar_regions update
+        for bar in self.bar_regions.iter_mut() {
+            if bar.addr() == params.new_base {
+                *bar = bar.set_address(params.old_base);
+            }
```
Comment (rbradford) [inline virtio-devices/src/transport/pci_device.rs]: I don't think this handles the 64-bit BARs correctly as they span two BARs

**Review by phip1611 — COMMENTED** [review]
My domain knowledge for PCI/Bar is limited. Using claude code, I've got the following remarks. They seem plausible, **but I'm not 100% sure**. WDYT?

- **`restore_bar_addr` 64-bit BAR matching is wrong** (`pci/src/configuration.rs`): The arm
  `(u64::from(bar.addr) << 32) == params.new_base` shifts the low-half value rather than reading the adjacent high-half BAR slot. Mirror `detect_bar_reprogramming`'s index-based logic and write back both `bars[i]`/`bars[i+1]` with a proper high/low split instead of a bare `old_base as u32`.

- **`bar_regions` rollback loop is likely dead code** (`virtio-devices/src/transport/pci_device.rs`):
  If `move_bar` failed before touching `bar_regions` the loop silently no-ops, making the comment "Undo move_bar's bar_regions update" misleading. Confirm whether `move_bar` can partially update `bar_regions`; if not, drop the loop.

- **Patch ordering breaks bisectability**: Patch 2 relies on `end` being inclusive, but that convention isn't established until patch 3. Swap the two so each commit is individually
  correct.

- **Document `end` as inclusive** (`create_mmio_allocators`): Add a doc comment to the function signature so future callers don't repeat the same off-by-one.

**Comment by rbradford** [comment]
> My domain knowledge for PCI/Bar is limited. Using claude code, I've got the following remarks. They seem plausible, **but I'm not 100% sure**. WDYT?
> 
> * **`restore_bar_addr` 64-bit BAR matching is wrong** (`pci/src/configuration.rs`): The arm
>   `(u64::from(bar.addr) << 32) == params.new_base` shifts the low-half value rather than reading the adjacent high-half BAR slot. Mirror `detect_bar_reprogramming`'s index-based logic and write back both `bars[i]`/`bars[i+1]` with a proper high/low split instead of a bare `old_base as u32`.

Indeed! That's what I flagged up too.

**Comment by rbradford** [comment]
@CMGS Please can you rebase to get rid of the merge commit

**Comment by CMGS** [comment]
@rbradford done with rebase, thanks

File: pci/src/device.rs [hunk 2]
```diff
@@ -93,6 +93,10 @@ pub trait PciDevice: Send {
     fn move_bar(&mut self, _old_base: u64, _new_base: u64) -> result::Result<(), io::Error> {
         Ok(())
     }
+    /// Restore BAR address in config space after a failed move_bar.
+    /// This rolls back the address update made by detect_bar_reprogramming()
+    /// so that the config register stays consistent with the MMIO bus mapping.
+    fn restore_bar_addr(&mut self, _params: &BarReprogrammingParams) {}
```
Comment (rbradford) [inline pci/src/device.rs:99]: Is it possible for you to implement this for VFIO too? Currently it's only implemented here for the virtio devices:

```
  diff --git a/pci/src/vfio.rs b/pci/src/vfio.rs
  index 51e3aa927..xxxxx 100644                                                                                                                                                                                                                                                                                               
  --- a/pci/src/vfio.rs                                                                                                                                                                                                                                                                                                       
  +++ b/pci/src/vfio.rs                                                                                                                                                                                                                                                                                                       
  @@ -2003,6 +2003,10 @@ impl PciDevice for VfioPciDevice {                                                                                                                                                                                                                                                                   
           Ok(())                                                                                                                                                                                                                                                                                                             
       }                                                                                                                                                                                                                                                                                                                      
                                                            
  +    fn restore_bar_addr(&mut self, params: &BarReprogrammingParams) {                                                                                                                                                                                                                                                      
  +        self.common.configuration.restore_bar_addr(params);
  +    }                                                                                                                                                                                                                                                                                                                      
  +                                                         
       fn as_any_mut(&mut self) -> &mut dyn Any {                                                                                                                                                                                                                                                                             
           self                                             
       }
```

Comment (rbradford) [reply pci/src/device.rs:99]: I looked a bit further and there are in total 6 implementations of this trait and so they all need updating in the same way.

Comment (CMGS) [reply pci/src/device.rs:99]: added in latest commit, thanks

Comment (rbradford) [reply pci/src/device.rs:99]: Thanks but I think it makes most sense to squash it into the commit that added it for virtio or put the virtio one into that last commit (my preference). Having it being enabled in the same way spread across two commits is a bit weird.

Comment (CMGS) [reply pci/src/device.rs:99]: done with rebase
