### PR TITLE
scripts: use arch OVMF downloads and bump fw tag

### LINKED ISSUE #7622: Bump and Unify edk2 Version for AArch64/x86_64
### Context
- Reference repo outdated: [cloud-hypervisor/edk2](https://github.com/cloud-hypervisor/edk2)
- Fix a sporadic VM boot hang:  [cloud-hypervisor wedges on boot before reaching kernel boot stage](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6779)
- Compilation broken on `AArch64`: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7609

### Proposal
- Align and update both AArch64 and x86_64 edk2 versions to a common, up-to-date commit or tag. 
- Ensure docs and scripts remain consistent across architectures. 
- (Stretch goal) Add/standardize a workflow so both x86_64 and AArch64 edk2 artifacts can be reliably built from our  [cloud-hypervisor/edk2](https://github.com/cloud-hypervisor/edk2) reference repo.

### Benefits
- Consistent build/test experience for all architectures.
- Reduced technical debt and easier ongoing upgrades.
- Enables contributors and CI to build/consume the proper firmware artifacts.

### PR DESCRIPTION
**Pull request by saravan2**
* Rename download_ovmf to download_amd64_ovmf and add a separate
download_aarch64_ovmf for CLOUDHV_EFI.fd

* Replace build_edk2 with download_aarch64_ovmf in aarch64 scripts

* Update OVMF firmware tag to ch-1e1b96f126

* Update CLOUDHV.fd sha1sum in sha1sums-x86_64

* Add CLOUDHV_EFI.fd sha1sum in sha1sums-aarch64-common

Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/7622

### Validation
arm64 Integration Test
https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/24222849244
amd64 Integration Test
https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/24222849230
MSHV Integration Test
https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/24222849227
Quality Check
https://github.com/cloud-hypervisor/cloud-hypervisor/actions/runs/24222849238

### CODE REVIEW

File: scripts/sha1sums-x86_64 [hunk 1]
```diff
@@ -1,3 +1,3 @@
 d4a44acc6014d5f83dea1c625c43d677a95fa75f alpine-minirootfs-x86_64.tar.gz
 540ac358429305d7aa94e15363665d1c9d845982 hypervisor-fw
-cf89e3e052c8ef0b6192abee6128eef943393307 CLOUDHV.fd
```
Comment (likebreath) [inline scripts/sha1sums-x86_64:3]: Can you add a hash to the newly added `CLOUDHV_EFI.fd` file too?

File: scripts/test-util.sh [hunk 2]
```diff
@@ -198,16 +198,26 @@ prepare_linux() {
     fi
 }
 
-download_ovmf() {
-    OVMF_FW_TAG="ch-13b4963ec4"
-    OVMF_FW_URL="https://github.com/cloud-hypervisor/edk2/releases/download/$OVMF_FW_TAG/CLOUDHV.fd"
+download_amd64_ovmf() {
+    OVMF_FW_TAG="release-build"
```
Comment (likebreath) [inline scripts/test-util.sh]: Nit: let's move the variable out of each function and reuse them between x86_64 and AArm64 to ensure they are unified all the time.

File: scripts/test-util.sh [hunk 3]
```diff
@@ -198,16 +198,26 @@ prepare_linux() {
...
+    OVMF_FW_URL="https://github.com/saravan2/edk2/releases/download/$OVMF_FW_TAG/CLOUDHV.fd"
     OVMF_FW="$WORKLOADS_DIR/CLOUDHV.fd"
     pushd "$WORKLOADS_DIR" || exit
     rm -f "$OVMF_FW"
     download_with_retries $OVMF_FW_URL || exit 1
     popd || exit
 }
 
+download_aarch64_ovmf() {
+    OVMF_FW_TAG="release-build"
```
Comment (likebreath) [inline scripts/test-util.sh]: Ditto.

**Review by likebreath — COMMENTED** [review]
Here is the new release (that matches the testing release you did from your fork): https://github.com/cloud-hypervisor/edk2/releases/tag/ch-1e1b96f126

Please update the PR and drop the testing (second) commit. I think we are ready to use the PR pipeline to validate the x86_64 works and let MQ validate the aarch64 works.

Also some minor comments below.

Thank you!

**Comment by saravan2** [comment]
@likebreath I will update this draft PR to source firmware from https://github.com/cloud-hypervisor/edk2/releases/tag/ch-1e1b96f126, remove the scaffolding commit and open this PR for review.

File: scripts/sha1sums-x86_64 (hunk 1 above)
Comment (likebreath) [reply scripts/sha1sums-x86_64:3]: This one is not addressed. Otherwise, looks good.

Comment (saravan2) [reply scripts/sha1sums-x86_64:3]: @likebreath We never had arm64 firmware `CLOUDHV_EFI.fd` sha1sum stored in `sha1sums-aarch64-common`
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/scripts/sha1sums-aarch64-common

If we are going to introduce sha1sum for `CLOUDHV_EFI.fd` then we would have to move the download_arm64_ovmf invocations and ensure that it completes before `sha1sums-aarch64-common --check`.

Comment (likebreath) [reply scripts/sha1sums-x86_64:3]: Yes, please. We didn't have the SHA check as the firmware was built from source.

**Review by likebreath — APPROVED** [review]

**Review by rbradford — APPROVED** [review]
