### PR TITLE
virtio-device: Mapping mmio over virtio-iommu

### LINKED ISSUE #6110: Nested virtualization not working with VFIO devices.
**Describe the bug**
Nested virtualization does not seem to be working correctly with VFIO devices. When creating a L1 cloud-hypervisor VM with a VFIO passthrough device and a L2 qemu VM with a VFIO passthrough device, the L1 VM exited with an error originating in the VfioDmaMapping::map function. Specifically, the problem seems to be with mapping the VFIO bars into the L2 VM memory space. See error log below.

**To Reproduce**

Start L1 virtual-machine.
```
target/debug/cloud-hypervisor \
  --kernel /var/lib/cloud-hypervisor/CLOUDHV.fd \
   --cpus boot=12,topology=2:6:1:1 \
   --memory size=4G \
   --disk path=~/ubuntu.raw \
   --net "tap=" \
   --console off \
   --device path=/sys/bus/pci/devices/0000:01:00.0,iommu=on \
   -v
```

Start L2 virtual machine.
```
/usr/bin/qemu-system-x86_64 \
-M type=q35,accel=kvm -nographic \
-cpu host \
-smp 12 \
-m 1G \
-drive file=/var/lib/cloud-hypervisor/jammy-server-cloudimg-amd64.img,format=qcow2 \
-device vfio-pci,host=0000:00:04.0 \
-net none
```

Guest OS version details:
Ubuntu 22.04

Host OS version details:
Ubuntu 22,04

**Logs**
Note that `0xe000180000` is the address of the PCI BAR of the VFIO passthrough device in the L1 guest. 

```
failed to convert guest address 0xe000180000 into host user virtual address
```

Linux kernel output:
```
[19056.136978] vfio-pci 0000:01:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0023 address=0xbe109000 flags=0x0000]
[19056.136983] vfio-pci 0000:01:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0023 address=0xbe109000 flags=0x0000]
[19056.136990] vfio-pci 0000:01:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0023 address=0xbe109000 flags=0x0000]
```

### PR DESCRIPTION
**Pull request by acarp-crusoe**
Add infrastructure to lookup the host address for mmio regions on external dma mapping requests. This specifically resolves vfio passthrough for virtio-iommu, allowing for nested virtualization to pass external devices through.

Fixes #6110

### CODE REVIEW

**Comment by rbradford** [comment]
@acarp-crusoe If a commit fixes a bug please can you put "Fixes: #<bug>" in the commit message itself - if it's just relevant "See: #<bug>"

**Comment by acarp-crusoe** [comment]
> @acarp-crusoe If a commit fixes a bug please can you put "Fixes: #" in the commit message itself - if it's just relevant "See: #"

Commit message has been updated to include the fixed bug - thanks

**Comment by acarp-crusoe** [comment]
From what I can see, the existing workflow also appears to be failing on the main branch so there's not much I can do to address that. Everything else is ready to go though

**Comment by rbradford** [comment]
@thomasbarrett would you like to review?

**Review by rbradford — COMMENTED** [review]
@acarp-crusoe This PR also has some extra whitespace changes - do you mind taking a look?

**Comment by acarp-crusoe** [comment]
> @acarp-crusoe This PR also has some extra whitespace changes - do you mind taking a look?

Sorry about that, whitespace changes should be reverted

File: pci/src/vfio.rs [hunk 1]
```diff
@@ -1885,3 +1898,88 @@ impl Snapshottable for VfioPciDevice {
...
+        let mem = self.memory.memory();
+        let guest_addr = GuestAddress(gpa);
+        let user_addr = 'block: {
+            // Check if the address is within RAM
+            if mem.check_range(guest_addr, size as usize) {
+                break 'block mem.get_host_address(guest_addr).unwrap() as u64;
+            }
+
+            // Check if the address is within an mmio region
+            for region in self.mmio_regions.lock().unwrap().iter() {
```
Comment (thomasbarrett) [inline pci/src/vfio.rs:1941]: I think that this logic would benefit from some simplification. (e.g.)
```rust
if mem.check_range(guest_addr, size as usize) {
    mem.get_host_address(guest_addr).unwrap() as u64;
} else if mmio_regions.check_range(guest_addr, size as usize) {
    mmio_regions.get_host_address(guest_addr).unwrap() as u64;
} else {
   return error
}
```

**Comment by thomasbarrett** [comment]
It seems like we are finding ourselves needing to re-implementing a lot of the functionality from the `vm_memory` crate for mmio. It would be great if we could re-use the functionality from `vm_memory` (all of which applies to mmio as well as physical RAM). This is more of an observation... I don't think that we need to look into this for this PR.

**Review by rbradford — APPROVED** [review]

**Comment by rbradford** [comment]
@thomasbarrett Are you happy with this PR - you can give your review

**Comment by thomasbarrett** [comment]
Sorry for the slow review @rbradford. @acarp-crusoe and I were at a conference :)

File: pci/src/vfio.rs (hunk 1 above)
Comment (acarp-crusoe) [reply pci/src/vfio.rs]: Yep that makes sense, this should be addressed - check_range and get_host_address methods have both been created for Vec<MmioRegions>

**Review by thomasbarrett — CHANGES_REQUESTED** [review]

File: pci/src/vfio.rs [hunk 2]
```diff
@@ -274,6 +275,57 @@ pub struct MmioRegion {
     pub(crate) index: u32,
     pub(crate) user_memory_regions: Vec<UserMemoryRegion>,
 }
+
+trait MmioRegionRange {
+    fn check_range(&self, guest_addr: u64, size: u64) -> bool;
```
Comment (thomasbarrett) [inline pci/src/vfio.rs:280]: nit: it might be good to the the `GuestAddress` and `GuestUSize` types in this trait.

File: pci/src/vfio.rs [hunk 3]
```diff
@@ -274,6 +275,57 @@ pub struct MmioRegion {
...
+    fn find_user_address(&self, guest_addr: u64) -> Option<u64>;
+}
+
+impl MmioRegionRange for Vec<MmioRegion> {
+    // Check if a guest address is within the range of mmio regions
+    fn check_range(&self, guest_addr: u64, size: u64) -> bool {
```
[the remark this answers is not in the document]
Comment (acarp-crusoe) [reply pci/src/vfio.rs:286]: I agree on the checked_add so I'll add that in. However, the request may span more than one user region, so there's a need to validate that the request sits within either one or multiple regions. Just checking that the length of the user region encompasses the size of the region may not cover all cases

File: pci/src/vfio.rs (hunk 2 above)
Comment (acarp-crusoe) [reply pci/src/vfio.rs:280]: I was debating whether to do that, it seems implied that GuestAddress would be compatible and initialized with calls into the vm_memory library so I felt that it might be best to keep this separate. Additionally user_memory_region, which this references, utilizes u64 for its addresses.

File: pci/src/vfio.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (acarp-crusoe) [reply pci/src/vfio.rs:286]: Actually looking deeper at the check_range method in the vm_memory crate it does validate that the map request is within one region on the host, and the virtio iommu spec does guarantee it should be within a single "carving". I'll update this to match your suggested code above.

spec:
The range defined by virt_start and virt_end should be within the limits specified by input_range. Given phys_end = phys_start + virt_end−virt_start, the range defined by phys_start and phys_end should be within the guest-physical address space. This includes upper and lower limits, as well as any carving of guest-physical addresses for use by the host. Guest physical boundaries are set by the host in a platform specific way.

**Review by likebreath — COMMENTED** [review]
Thank you for the contribution. I'd suggest to split this change into two commits. The first commit is refactoring (e.g. no functional change) of  moving `VfioDmaMapping` to the `pci` crate. And the second commit (the actual functional change) is extending the `VfioDmamapping` struct to support lookup the user address of mmio regions. Separating functional changes from refactoring is generally cleaner and can help a lot with code review.

Also, I wonder why a Cloud Hypervisor L2 VM works while a QEMU L2 VM does not work?  Parden me that I have limited understanding of VFIO and vMMIO.

File: vmm/src/device_manager.rs [hunk 4]
```diff
@@ -3530,6 +3534,10 @@ impl DeviceManager {
             .map_mmio_regions()
             .map_err(DeviceManagerError::VfioMapRegion)?;
 
+        for mmio_region in vfio_pci_device.lock().unwrap().mmio_regions() {
+            self.mmio_regions.lock().unwrap().push(mmio_region);
```
[the remark this answers is not in the document]
Comment (acarp-crusoe) [reply vmm/src/device_manager.rs:3538]: I'm working on getting hotplug working right now, currently it doesn't work at all with nested virtualization for mmio. I'll follow that up in a separate PR

[the remark this answers is not in the document]
Comment (acarp-crusoe) [reply vmm/src/device_manager.rs:3538]: That said, your comment should still be addressed in this PR, it now removes entries properly from the mmio regions when a device is hot removed.

Hot add makes sense to follow up in a different PR

**Comment by acarp-crusoe** [comment]
> Thank you for the contribution. I'd suggest to split this change into two commits. The first commit is refactoring (e.g. no functional change) of moving `VfioDmaMapping` to the `pci` crate. And the second commit (the actual functional change) is extending the `VfioDmamapping` struct to support lookup the user address of mmio regions. Separating functional changes from refactoring is generally cleaner and can help a lot with code review.
> 
> Also, I wonder why a Cloud Hypervisor L2 VM works while a QEMU L2 VM does not work? Parden me that I have limited understanding of VFIO and vMMIO.

Sounds good, the change has just been split into two commits (one the refactor and the other functional),  just let me know if you'd need anything else.

And to answer your question - both Cloud Hypervisor and Qemu worked as L2 VMs within Cloud Hypervisor. However, if you tried to include any external pci devices as part of the L2 VM, that wouldn't work. The issue lied in the fact that the mapping requests that arrived in the virtio iommu device did not check against mmio regions at all within VfioDmaMapping. Originally VfioDmaMapping just attempted to dma map RAM using the guest_memory mmap stored in the memory_manager, but mmio regions are not included in the guest_memory  mmap. This PR adds mmio_regions as a separate object in the device_manager so the VfioDmaMapping is able to check both guest memory (RAM) as well as mmio. With this change, we can now map mmio over virtio iommu properly, whereas before the L1 VM would crash because it receiving a mapping request for a band of mmio memory it couldn't locate.

File: pci/src/vfio.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (likebreath) [reply pci/src/vfio.rs:286]: It makes sense to me that a DMA mapping needs to be continuous on the host side and hence should be within a single region in the guest (no matter it is GuestMemoryRegion or a MMIORegion). 

> Actually looking deeper at the check_range method in the vm_memory crate it does validate that the map request is within one region on the host, 

I came to a different conclusion after reading its implementation from vm_memory crate. I believe `vm_memory::guest_memory::GuestMemory::check_range()` returns true as long as the range is valid even if the given range is backed by multiple regions. Please take another look here: https://github.com/rust-vmm/vm-memory/blob/b8bf1dbcca5d85a158cf7a8ed6cb19774428819c/src/guest_memory.rs#L648-L651.

If I am right, we have a bug here with using `GuestMemory::check_range()`.

File: pci/src/vfio.rs [hunk 5]
```diff
@@ -1912,6 +1956,13 @@ impl<M: GuestAddressSpace + Sync + Send> ExternalDmaMapping for VfioDmaMapping<M
         let guest_addr = GuestAddress(gpa);
         let user_addr = if mem.check_range(guest_addr, size as usize) {
             mem.get_host_address(guest_addr).unwrap() as u64
+        } else if self.mmio_regions.lock().unwrap().check_range(gpa, size) {
+            self.mmio_regions
+                .lock()
+                .unwrap()
+                .find_user_address(gpa)
+                .ok_or("unable to locate user addr for mmio region")
+                .unwrap()
```
Comment (likebreath) [inline pci/src/vfio.rs:1965]: Nit: Instead of using `unwrap()`, it is better to return an Error with the failing `gpa`, so that the Cloud Hypervisor process won't be aborted yet providing some information for debugging. You can take the following `else` statement as a reference.

File: pci/src/vfio.rs [hunk 6]
```diff
@@ -275,6 +275,41 @@ pub struct MmioRegion {
...
+    fn find_user_address(&self, guest_addr: u64) -> Option<u64>;
+}
+
+impl MmioRegionRange for Vec<MmioRegion> {
+    // Check if a guest address is within the range of mmio regions
+    fn check_range(&self, guest_addr: u64, size: u64) -> bool {
+        for region in self.iter() {
+            if guest_addr >= region.start.raw_value()
+                && guest_addr.checked_add(size).unwrap()
+                    <= region.start.raw_value().checked_add(region.length).unwrap()
```
Comment (likebreath) [inline pci/src/vfio.rs:290]: Similarly, it would be good to avoid using unwrap(). You can return `false` for when `checked_add()` failed.

**Review by likebreath — COMMENTED** [review]
The code changes make sense and look good to me. As I am not an VFIO expert,  another review will be very helpful. @rbradford @thomasbarrett

**Comment by likebreath** [comment]
> And to answer your question - both Cloud Hypervisor and Qemu worked as L2 VMs within Cloud Hypervisor. However, if you tried to include any external pci devices as part of the L2 VM, that wouldn't work. 

This makes sense if both Cloud Hypervisor and QEMU L2 VM with VFIO devices are failing. I thought the observation was that L2 Cloud Hypervisor with VFIO works according to this comment: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6110#issuecomment-1915382047. Thanks for clarifying that.

File: pci/src/vfio.rs (hunk 5 above)
Comment (acarp-crusoe) [reply pci/src/vfio.rs]: Noted - I've removed the `unwrap()` usage and returned a more helpful message for the error case (for both the guest_memory and mmio checks)

File: pci/src/vfio.rs (hunk 6 above)
Comment (acarp-crusoe) [reply pci/src/vfio.rs]: Done, this should now return `false` if `checked_add()` fails

File: pci/src/vfio.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (acarp-crusoe) [reply pci/src/vfio.rs:286]: Hmmm I see what you're saying, I don't see anything in the vm_memory crate that allows the caller to ensure the range is within one region. However, I could optionally utilize the `find_region` method instead and then do my own size comparison, something like:

```
        let region = mem.find_region(guest_addr);
        let user_addr = if region.is_some() && size <= region.unwrap().len() {
                // call mem.get_host_address here
```

File: vmm/src/device_manager.rs [hunk 7]
```diff
@@ -4201,12 +4209,21 @@ impl DeviceManager {
...
             // No need to remove any virtio-mem mapping here as the container outlives all devices
-            PciDeviceHandle::Vfio(vfio_pci_device) => (
-                Arc::clone(&vfio_pci_device) as Arc<Mutex<dyn PciDevice>>,
-                Arc::clone(&vfio_pci_device) as Arc<Mutex<dyn BusDevice>>,
-                None as Option<Arc<Mutex<dyn virtio_devices::VirtioDevice>>>,
-                false,
-            ),
+            PciDeviceHandle::Vfio(vfio_pci_device) => {
+                for mmio_region in vfio_pci_device.lock().unwrap().mmio_regions() {
+                    self.mmio_regions
```
Comment (thomasbarrett) [inline vmm/src/device_manager.rs:4214]: It might be better to just put this in the `drop` method for vfio_pci_device.

**Comment by acarp-crusoe** [comment]
> > And to answer your question - both Cloud Hypervisor and Qemu worked as L2 VMs within Cloud Hypervisor. However, if you tried to include any external pci devices as part of the L2 VM, that wouldn't work.
> 
> This makes sense if both Cloud Hypervisor and QEMU L2 VM with VFIO devices are failing. I thought the observation was that L2 Cloud Hypervisor with VFIO works according to this comment: [#6110 (comment)](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6110#issuecomment-1915382047). Thanks for clarifying that.

No problem, and that previous comment you've linked was when I was trying to get an understanding of the bug that @thomasbarrett produced, so it's actually a little off. I added a followup comment to clarify the behavior of the bug now that we have a good understanding.

File: pci/src/vfio.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (likebreath) [reply pci/src/vfio.rs:286]: Right. This would be how I fix it. I opened an issue for this potential bug (#6329). Please feel free to revise the issue and open a separate PR to fix it. Thanks.

File: pci/src/vfio.rs [hunk 8]
```diff
@@ -275,6 +275,48 @@ pub struct MmioRegion {
...
+                {
+                    return Ok(user_region.host_addr + (guest_addr - user_region.start));
+                }
+            }
+        }
+
+        Err(io::Error::new(
+            io::ErrorKind::Other,
+            "unable to find user address",
+        ))
```
Comment (likebreath) [inline pci/src/vfio.rs:316]: Better to embed the `gpa` in the Error message for debugging purposes.

File: pci/src/vfio.rs [hunk 9]
```diff
@@ -1911,14 +1962,29 @@ impl<M: GuestAddressSpace + Sync + Send> ExternalDmaMapping for VfioDmaMapping<M
...
+        } else if self.mmio_regions.lock().unwrap().check_range(gpa, size) {
+            match self.mmio_regions.lock().unwrap().find_user_address(gpa) {
+                Ok(t) => t,
+                Err(e) => {
+                    return Err(io::Error::new(
+                        io::ErrorKind::Other,
+                        format!("unable to retrieve user address for gpa 0x{gpa:x} in mmio regions: {e}")
+                    ));
+                }
+            }
```
Comment (likebreath) [inline pci/src/vfio.rs:1983]: You should be able to simply do: `self.mmio_regions.lock().unwrap().find_user_address(gpa)?`

**Review by likebreath — COMMENTED** [review]
Few more comments below. Also, it is good to use verb to start the commit message. Say:

`virtio-devices: Move VfioDmaMapping to be in the pci crate`
`virtio-devices: Map mmio over virtio-iommu`

File: vmm/src/device_manager.rs (hunk 7 above)
Comment (acarp-crusoe) [reply vmm/src/device_manager.rs:4214]: I thought about that, but it seemed like it broke OO convention to modify something the device manager tracks from a different crate. Especially given it's built/modified already by the device manager itself.

**Comment by likebreath** [comment]
The PR looks good to me. @thomasbarrett @rbradford And additional comments?

**Review by rbradford — APPROVED** [review]

**Comment by thomasbarrett** [comment]
No additional comments. Looks good to me :)
