### PR TITLE
virtio-console: Fix lost output when connected to a PTY

### LINKED ISSUE #4521: virtio-console: Output to the PTY partially lost
Similarly to what was described on #3170, when the `virtio-console` device is connected to a PTY device, some of the output is lost.
This is because we should wait for the other end of the PTY device to be connected before trying to write some output to it. While it's disconnected, we must simply buffer the output.

### PR DESCRIPTION
**Pull request by sboeuf**
Through multiple changes, this PR aims at providing a reliable solution for detecting the state of the PTY's connection. Being able to find out when the other end of the PTY is connected is essential to prevent the loss of data being output through the PTY. When the PTY isn't connected, the output is buffered through the SerialBuffer, the same solution that was created for the serial port initially.

Fixes #4521

### CODE REVIEW

File: virtio-devices/src/console.rs [hunk 1]
```diff
@@ -332,6 +473,46 @@ impl EpollHelperHandler for ConsoleEpollHandler {
...
+
+            // This very specific case happens when the console is connected
+            // to a PTY. We know EPOLLHUP is always present when there's nothing
+            // connected at the other end of the PTY. That's why getting no event
+            // means we can flush the output of the console through the PTY.
+            self.trigger_pty_flush()
+                .map_err(EpollHelperError::HandleTimeout)?;
+        }
+
+        self.register_file_event(helper)
```
Comment (likebreath) [inline virtio-devices/src/console.rs:514]: I wonder why we need to register the file event here? I thought it would be enough to check if the pty is connected every 500ms (after the last processed epoll event) by using `handle_timeout()`

File: virtio-devices/src/console.rs [hunk 2]
```diff
@@ -332,6 +473,46 @@ impl EpollHelperHandler for ConsoleEpollHandler {
...
+        if self.file_event_registered {
+            // This very specific case happens when the console is connected
+            // to a PTY. We know EPOLLHUP is always present when there's nothing
+            // connected at the other end of the PTY. That's why getting no event
+            // means we can flush the output of the console through the PTY.
+            self.trigger_pty_flush()
+                .map_err(EpollHelperError::HandleTimeout)?;
+        }
+
+        self.register_file_event(helper)
```
Comment (likebreath) [inline virtio-devices/src/console.rs:491]: It is good to have some comments here. My understanding is that this is for re-checking if a pty is connected every 500ms (the epoll timeout).

File: virtio-devices/src/console.rs [hunk 3]
```diff
@@ -332,6 +473,46 @@ impl EpollHelperHandler for ConsoleEpollHandler {
...
+    }
+
+    fn event_list(
```
Comment (likebreath) [inline virtio-devices/src/console.rs:494]: It would be good to have some comments to explain what `event_list()` does. My understanding is that it is for flushing buffered pty output as soon as possible, e.g. do not wait until we have the next `EPOLLIN` 'file event'.

**Review by likebreath — COMMENTED** [review]
I took me a while to understand how the PR works in terms of detecting PTY connection/disconnection. Below are a few comments/questions based my understanding.

File: virtio-devices/src/console.rs (hunk 2 above)
Comment (sboeuf) [reply virtio-devices/src/console.rs:491]: I'll add a comment.

File: virtio-devices/src/console.rs (hunk 3 above)
Comment (sboeuf) [reply virtio-devices/src/console.rs:494]: I've added a comment.

File: virtio-devices/src/console.rs (hunk 1 above)
Comment (sboeuf) [reply virtio-devices/src/console.rs:514]: The problem if we rely exclusively on `handle_timeout()` is that other events (INPUT_QUEUE_EVENT, OUTPUT_QUEUE_EVENT, ...) can be triggered (especially at boot when the driver provides a bunch of descriptors to the backend), and they directly impact the ability to detect a connection because the timeout will not be triggered unless there NO event at all.

File: vmm/src/device_manager.rs [hunk 4]
```diff
@@ -492,7 +492,7 @@ pub fn create_pty(non_blocking: bool) -> io::Result<(File, File, PathBuf)> {
     // See https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
     // for further details.
 
-    let custom_flags = libc::O_NOCTTY | if non_blocking { libc::O_NONBLOCK } else { 0 };
+    let custom_flags = libc::O_NONBLOCK;
```
[the remark this answers is not in the document]
Comment (sboeuf) [reply vmm/src/device_manager.rs:495]: Oh yes I've done that because it doesn't make sense to apply this flag on the ptmx side of the PTY. You can refer to what `glibc` does here: https://elixir.bootlin.com/glibc/glibc-2.36/source/sysdeps/unix/sysv/linux/getpt.c#L38

The `O_NOCTTY` flag makes sense for the other end of the PTY, which we don't want to set as the controlling terminal.

File: vm-device/src/lib.rs [hunk 5]
```diff
@@ -10,6 +10,7 @@ use serde::{Deserialize, Serialize};
 mod bus;
 pub mod dma_mapping;
 pub mod interrupt;
+pub mod serial_buffer;
```
Comment (rbradford) [inline vm-device/src/lib.rs:13]: Urgh, i'm not sure this is a good idea. This really overloads the meaning of the crate. I know it's only a short bit of code but it would be better it it's own crate.

File: virtio-devices/src/epoll_helper.rs [hunk 6]
```diff
@@ -47,6 +49,18 @@ pub trait EpollHelperHandler {
...
+    }
+
+    fn event_list(
+        &mut self,
+        _helper: &mut EpollHelper,
+        _events: &[epoll::Event],
+    ) -> Result<(), EpollHelperError> {
+        Ok(())
+    }
 }
```
Comment (rbradford) [inline virtio-devices/src/epoll_helper.rs:64]: At this point I think the methods on this trait need explanatory documentation.

**Review by rbradford — APPROVED** [review]
Cool. Pleased you got it working!

File: virtio-devices/src/epoll_helper.rs (hunk 6 above)
Comment (sboeuf) [reply virtio-devices/src/epoll_helper.rs:64]: Sure!

**Review by rbradford — APPROVED** [review]
