### PR TITLE
virtio-devices: Forward correct evset in vsock muxer

### LINKED ISSUE #3497: vsock: unexpected EWOULDBLOCK while reading from backing stream
cloud-hypervisor v20.1.0

--vsock cid=3,socket=/path/v.sock

Reproduced with streaming uncompressed video/assets over waypipe (wayland over sockets)
Frequency of occurrence depends on size of window (and therefore bandwidth)

On host:
waypipe --socket /path/v.sock_5000 client &

On guest:
socat UNIX-LISTEN:/tmp/waypipe-server.sock,reuseaddr,fork VSOCK-CONNECT:2:5000,forever &
waypipe --no-gpu --socket /tmp/waypipe-server.sock --control /tmp/waypipe-ctrl.pipe --display /tmp/wayland-0 server -- sleep inf &
WAYLAND_DISPLAY=/tmp/wayland-0 mpv /path/to/4k_video.mp4

```
cloud-hypervisor: 1155.939756072s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.142021665s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.1425842s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.143808813s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.189278481s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.412921305s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.563153059s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.564757199s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```
This times 1000.

### PR DESCRIPTION
**Pull request by sboeuf**
When forwarding an epoll event from the unix muxer to the
targeted connection event handler, the eventset the connection
registered is forwarded instead of the actual epoll
operation (IN/OUT).

For example, if the connection was registered for EPOLLIN,
and receives an EPOLLOUT, the connection will actually handle
an EPOLLOUT.

This is the root cause of previous bug, which caused the
introduction of some workarounds (i.e: handling ewouldblock
when reading after receiving EPOLLIN, which should never happen).

When matching the connection, we retrieve and use the evset of
the connection instead of the one passed as a parameter.
The compiler does not complain for an unused variable because
it was first logged in a debug! statement.

This is an unfortunate naming mistake that caused a lot of problems.

Signed-off-by: Eduard Kyvenko <eduard.kyvenko@gmail.com>
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

Fixes #3497

### CODE REVIEW

File: virtio-devices/src/vsock/unix/muxer.rs [hunk 1]
```diff
@@ -362,25 +362,24 @@ impl VsockMuxer {
 
     /// Handle/dispatch an epoll event to its listener.
     ///
-    fn handle_event(&mut self, fd: RawFd, evset: epoll::Events) {
+    fn handle_event(&mut self, fd: RawFd, event_set: epoll::Events) {
         debug!(
             "vsock: muxer processing event: fd={}, evset={:?}",
-            fd, evset
+            fd, event_set
```
Comment (rbradford) [inline virtio-devices/src/vsock/unix/muxer.rs:368]: If you're going to change the variable name you should change the debug statement about that variable.

File: virtio-devices/src/vsock/unix/muxer.rs [hunk 2]
```diff
@@ -443,7 +442,10 @@ impl VsockMuxer {
             }
 
             _ => {
-                info!("vsock: unexpected event: fd={:?}, evset={:?}", fd, evset);
+                info!(
+                    "vsock: unexpected event: fd={:?}, evset={:?}",
+                    fd, event_set
```
Comment (rbradford) [inline virtio-devices/src/vsock/unix/muxer.rs:447]: Ditto.

File: virtio-devices/src/vsock/unix/muxer.rs (hunk 1 above)
Comment (sboeuf) [reply virtio-devices/src/vsock/unix/muxer.rs:368]: Done

File: virtio-devices/src/vsock/unix/muxer.rs (hunk 2 above)
Comment (sboeuf) [reply virtio-devices/src/vsock/unix/muxer.rs:447]: Done

**Review by rbradford — APPROVED** [review]
